experimentalTernaries: true
plugins:
  - ./node_modules/prettier-plugin-organize-imports/index.js
  - ./packages/prettier-plugin-alloy/dist/index.js
overrides:
  - files: "**/*.tsx"
    options:
      parser: alloy-ts
  - files: "packages/dev-tools/**/*.tsx"
    options:
      parser: typescript
