packages:
  - packages/*
  - samples/*
  - test/*

allowBuilds:
  core-js: false
  esbuild: true
  sharp: false

catalog:
  "@astrojs/check": ^0.9.6
  "@astrojs/starlight": ^0.39.3
  "@babel/cli": ^7.24.7
  "@babel/core": 7.29.7
  "@babel/generator": ^7.29.7
  "@babel/helper-module-imports": 7.29.7
  "@babel/plugin-syntax-jsx": ^7.29.7
  "@babel/preset-typescript": 7.29.7
  "@babel/types": ^7.29.7
  "@eslint/js": ^10.0.1
  "@radix-ui/react-context-menu": ^2.2.6
  "@radix-ui/react-dropdown-menu": ^2.1.6
  "@radix-ui/react-tabs": ^1.1.13
  "@radix-ui/react-toast": ^1.2.6
  "@rollup/plugin-babel": ^7.1.0
  "@rollup/plugin-node-resolve": ^16.0.3
  "@rollup/plugin-typescript": ^12.3.0
  "@tailwindcss/vite": ^4.1.18
  "@tanstack/react-virtual": ^3.13.6
  "@types/babel__core": ^7.20.5
  "@types/babel__generator": ^7.27.0
  "@types/babel__traverse": ^7.28.0
  "@types/dagre": ^0.7.53
  "@types/diff-match-patch": ^1.0.36
  "@types/js-yaml": ^4.0.9
  "@types/node": ^25.9.2
  "@types/prompts": ^2.4.9
  "@types/react": ^19.2.5
  "@types/react-dom": ^19.2.3
  "@types/ws": ^8.18.1
  "@typespec/compiler": ^1.0.0
  "@typespec/http": ^1.0.1
  "@vitejs/plugin-react": ^6.0.2
  "@vitest/eslint-plugin": ^1.6.19
  "@vue/reactivity": ^3.5.35
  astro: ^6.4.4
  astro-expressive-code: ^0.43.0
  babel-plugin-tester: ^12.0.0
  change-case: ^5.4.4
  class-variance-authority: ^0.7.1
  cli-table3: ^0.6.5
  clsx: ^2.1.1
  concurrently: ^10.0.3
  dagre: ^0.8.5
  devalue: ^5.8.1
  diff-match-patch: ^1.0.5
  eslint: ^10.4.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.5.2
  fast-xml-parser: ^5.8.0
  globals: ^17.6.0
  html-entities: 2.6.0
  js-yaml: ^4.1.0
  listr2: ^10.2.1
  lucide-react: ^1.17.0
  marked: ^18.0.5
  pathe: ^2.0.3
  picocolors: ^1.1.1
  prettier: ^3.8.3
  prettier-plugin-organize-imports: ^4.3.0
  prompts: ^2.4.2
  react: ^19.2.0
  react-dom: ^19.2.0
  react-resizable-panels: ^4.4.1
  rimraf: ^6.1.3
  rollup: ^4.61.1
  sharp: ^0.34.1
  starlight-llms-txt: ^0.10.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsx: ^4.22.4
  tw-animate-css: ^1.4.0
  typedoc: ^0.28.8
  typescript: ^6.0.3
  typescript-eslint: ^8.60.1
  validate-html-nesting: ^1.2.4
  vite: ^8.0.16
  vite-plugin-singlefile: ^2.3.0
  vitest: 4.1.8
  ws: ^8.21.0
  yaml: ^2.7.1
