packages:
  - packages/*
  - samples/*

catalog:
  "@babel/cli": ^7.24.7
  "@babel/core": ^7.24.7
  "@babel/generator": ^7.27.0
  "@babel/helper-module-imports": 7.27.1
  "@babel/plugin-syntax-jsx": ^7.18.6
  "@babel/preset-typescript": ^7.27.0
  "@babel/types": ^7.27.0
  "@eslint/js": ^9.32.0
  "@microsoft/api-extractor": ~7.52.8
  "@microsoft/api-extractor-model": ~7.30.6
  "@microsoft/tsdoc": 0.15.1
  "@rollup/plugin-babel": ^6.0.4
  "@rollup/plugin-node-resolve": ^16.0.1
  "@rollup/plugin-typescript": ^12.1.2
  "@types/babel__core": ^7.20.5
  "@types/babel__generator": ^7.6.8
  "@types/babel__traverse": ^7.20.7
  "@types/node": ^24.1.0
  "@vitest/eslint-plugin": ^1.3.4
  "@vue/reactivity": ^3.5.13
  babel-plugin-tester: ^12.0.0
  change-case: ^5.4.4
  cli-table3: ^0.6.5
  concurrently: ^9.2.0
  eslint: ^9.32.0
  html-entities: 2.6.0
  marked: ^16.1.1
  pathe: ^2.0.3
  picocolors: ^1.1.1
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.2.0
  rimraf: ^6.0.1
  rollup: ^4.39.0
  tsx: ^4.19.3
  typescript: ^5.8.3
  typescript-eslint: ^8.38.0
  validate-html-nesting: ^1.2.1
  vite: ^7.0.6
  vitest: ^3.2.4
