import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_ffi = {
  CString: {
    kind: "struct", metadata: { since: "1.64.0" },
    members: {
      as_bytes: { kind: "function", metadata: { since: "1.0.0" } },
      as_bytes_with_nul: { kind: "function", metadata: { since: "1.0.0" } },
      as_c_str: { kind: "function", metadata: { since: "1.20.0" } },
      from_raw: { kind: "function", associated: true, metadata: { since: "1.4.0" } },
      from_vec_unchecked: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      from_vec_with_nul: { kind: "function", associated: true, metadata: { since: "1.58.0" } },
      from_vec_with_nul_unchecked: { kind: "function", associated: true, metadata: { since: "1.58.0" } },
      into_boxed_c_str: { kind: "function", metadata: { since: "1.20.0" } },
      into_bytes: { kind: "function", metadata: { since: "1.7.0" } },
      into_bytes_with_nul: { kind: "function", metadata: { since: "1.7.0" } },
      into_raw: { kind: "function", metadata: { since: "1.4.0" } },
      into_string: { kind: "function", metadata: { since: "1.7.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
    },
  },
  FromVecWithNulError: {
    kind: "struct", metadata: { since: "1.64.0" },
    members: {
      as_bytes: { kind: "function", metadata: { since: "1.58.0" } },
      into_bytes: { kind: "function", metadata: { since: "1.58.0" } },
    },
  },
  IntoStringError: {
    kind: "struct", metadata: { since: "1.64.0" },
    members: {
      into_cstring: { kind: "function", metadata: { since: "1.7.0" } },
      utf8_error: { kind: "function", metadata: { since: "1.7.0" } },
    },
  },
  NulError: {
    kind: "struct", metadata: { since: "1.64.0" },
    members: {
      into_vec: { kind: "function", metadata: { since: "1.0.0" } },
      nul_position: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_ffi_c_str = {
  CString: {
    kind: "struct", metadata: { since: "1.64.0" },
    members: {
      as_bytes: { kind: "function", metadata: { since: "1.0.0" } },
      as_bytes_with_nul: { kind: "function", metadata: { since: "1.0.0" } },
      as_c_str: { kind: "function", metadata: { since: "1.20.0" } },
      from_raw: { kind: "function", associated: true, metadata: { since: "1.4.0" } },
      from_vec_unchecked: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      from_vec_with_nul: { kind: "function", associated: true, metadata: { since: "1.58.0" } },
      from_vec_with_nul_unchecked: { kind: "function", associated: true, metadata: { since: "1.58.0" } },
      into_boxed_c_str: { kind: "function", metadata: { since: "1.20.0" } },
      into_bytes: { kind: "function", metadata: { since: "1.7.0" } },
      into_bytes_with_nul: { kind: "function", metadata: { since: "1.7.0" } },
      into_raw: { kind: "function", metadata: { since: "1.4.0" } },
      into_string: { kind: "function", metadata: { since: "1.7.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
    },
  },
  FromVecWithNulError: {
    kind: "struct", metadata: { since: "1.64.0" },
    members: {
      as_bytes: { kind: "function", metadata: { since: "1.58.0" } },
      into_bytes: { kind: "function", metadata: { since: "1.58.0" } },
    },
  },
  IntoStringError: {
    kind: "struct", metadata: { since: "1.64.0" },
    members: {
      into_cstring: { kind: "function", metadata: { since: "1.7.0" } },
      utf8_error: { kind: "function", metadata: { since: "1.7.0" } },
    },
  },
  NulError: {
    kind: "struct", metadata: { since: "1.64.0" },
    members: {
      into_vec: { kind: "function", metadata: { since: "1.0.0" } },
      nul_position: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
