import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_fmt = {
  Alignment: { kind: "enum" },
  Arguments: { kind: "struct" },
  Binary: { kind: "trait" },
  Debug: { kind: "trait" },
  DebugAsHex: { kind: "enum" },
  DebugList: { kind: "struct" },
  DebugMap: { kind: "struct" },
  DebugSet: { kind: "struct" },
  DebugStruct: { kind: "struct" },
  DebugTuple: { kind: "struct" },
  Display: { kind: "trait" },
  Error: { kind: "struct" },
  format: { kind: "function", metadata: { since: "1.0.0" } },
  Formatter: { kind: "struct" },
  FormattingOptions: { kind: "struct" },
  from_fn: { kind: "function" },
  FromFn: { kind: "struct" },
  LowerExp: { kind: "trait" },
  LowerHex: { kind: "trait" },
  Octal: { kind: "trait" },
  Pointer: { kind: "trait" },
  Result: { kind: "type-alias" },
  Sign: { kind: "enum" },
  UpperExp: { kind: "trait" },
  UpperHex: { kind: "trait" },
  write: { kind: "function" },
  Write: { kind: "trait" },
} as const satisfies Record<string, SymbolDescriptor>;
