import { type SymbolCreator } from "@alloy-js/core";
import {
  type CrateDescriptor,
  type CrateRef,
  createCrate,
  type ExternalCrate,
} from "../../create-crate.js";
import { mod_alloc } from "./alloc.js";
import { mod_borrow } from "./borrow.js";
import { mod_boxed } from "./boxed.js";
import { mod_collections, mod_collections_binary_heap, mod_collections_linked_list, mod_collections_vec_deque } from "./collections.js";
import { mod_ffi, mod_ffi_c_str } from "./ffi.js";
import { mod_fmt } from "./fmt.js";
import { mod_rc } from "./rc.js";
import { mod_root } from "./root.js";
import { mod_slice } from "./slice.js";
import { mod_str, mod_str_pattern } from "./str.js";
import { mod_string } from "./string.js";
import { mod_sync } from "./sync.js";
import { mod_task } from "./task.js";
import { mod_vec } from "./vec.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

const allocDescriptor = {
  name: "alloc",
  builtin: true,
  modules: {
    "alloc": mod_alloc,
    "borrow": mod_borrow,
    "boxed": mod_boxed,
    "collections": mod_collections,
    "collections::binary_heap": mod_collections_binary_heap,
    "collections::linked_list": mod_collections_linked_list,
    "collections::vec_deque": mod_collections_vec_deque,
    "ffi": mod_ffi,
    "ffi::c_str": mod_ffi_c_str,
    "fmt": mod_fmt,
    "rc": mod_rc,
    "": mod_root,
    "slice": mod_slice,
    "str": mod_str,
    "str::pattern": mod_str_pattern,
    "string": mod_string,
    "sync": mod_sync,
    "task": mod_task,
    "vec": mod_vec,
  },
} as const satisfies CrateDescriptor;

/**
 * The `alloc` crate descriptor.
 */
export type AllocCrate = CrateRef<typeof allocDescriptor> &
  SymbolCreator &
  ExternalCrate;
export const alloc: AllocCrate = createCrate(allocDescriptor);
