import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_root = {
  format: { kind: "symbol", metadata: { since: "1.0.0" } },
  vec: { kind: "symbol", metadata: { since: "1.0.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
