import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_task = {
  local_waker_fn: { kind: "function", metadata: { since: "unstable" } },
  LocalWake: { kind: "trait", metadata: { since: "unstable" } },
  Wake: { kind: "trait", metadata: { since: "1.51.0" } },
  waker_fn: { kind: "function", metadata: { since: "unstable" } },
} as const satisfies Record<string, SymbolDescriptor>;
