import { SymbolCreator } from "@alloy-js/core";
import { createModule, type ModuleDescriptor } from "../create-module.js";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
type dummy = SymbolCreator;

export const abcModule = createModule({
  name: "abc",
  descriptor: {
    ".": ["abstractmethod"],
  },
});

export const dataclassesModule = createModule({
  name: "dataclasses",
  descriptor: {
    ".": ["dataclass", "KW_ONLY"],
  },
});

export const enumModule = createModule({
  name: "enum",
  descriptor: {
    ".": ["auto", "Enum", "Flag", "IntEnum", "IntFlag", "StrEnum"],
  },
});

export const requestsModule = createModule({
  name: "requests",
  descriptor: {
    ".": ["get", "post", "put", "delete", "patch", "head", "options"],
    models: ["Response", "Request"],
  },
});

// Descriptor source captured from pydantic 2.13.4 via script
const pydanticDescriptor = {
  ".": [
    "AfterValidator",
    "AliasChoices",
    "AliasGenerator",
    "AliasPath",
    "AllowInfNan",
    "AmqpDsn",
    "AnyHttpUrl",
    "AnyUrl",
    "AnyWebsocketUrl",
    "AwareDatetime",
    "Base64Bytes",
    "Base64Encoder",
    "Base64Str",
    "Base64UrlBytes",
    "Base64UrlStr",
    "BaseModel",
    "BeforeValidator",
    "ByteSize",
    "ClickHouseDsn",
    "CockroachDsn",
    "ConfigDict",
    "DirectoryPath",
    "Discriminator",
    "EmailStr",
    "EncodedBytes",
    "EncodedStr",
    "EncoderProtocol",
    "Extra",
    "FailFast",
    "Field",
    "FieldSerializationInfo",
    "FilePath",
    "FileUrl",
    "FiniteFloat",
    "FtpUrl",
    "FutureDate",
    "FutureDatetime",
    "GetCoreSchemaHandler",
    "GetJsonSchemaHandler",
    "GetPydanticSchema",
    "HttpUrl",
    "IPvAnyAddress",
    "IPvAnyInterface",
    "IPvAnyNetwork",
    "ImportString",
    "InstanceOf",
    "Json",
    "JsonValue",
    "KafkaDsn",
    "MariaDBDsn",
    "ModelWrapValidatorHandler",
    "MongoDsn",
    "MySQLDsn",
    "NaiveDatetime",
    "NameEmail",
    "NatsDsn",
    "NegativeFloat",
    "NegativeInt",
    "NewPath",
    "NonNegativeFloat",
    "NonNegativeInt",
    "NonPositiveFloat",
    "NonPositiveInt",
    "OnErrorOmit",
    "PastDate",
    "PastDatetime",
    "PaymentCardNumber",
    "PlainSerializer",
    "PlainValidator",
    "PositiveFloat",
    "PositiveInt",
    "PostgresDsn",
    "PrivateAttr",
    "PydanticDeprecatedSince20",
    "PydanticDeprecatedSince210",
    "PydanticDeprecatedSince211",
    "PydanticDeprecatedSince212",
    "PydanticDeprecatedSince26",
    "PydanticDeprecatedSince29",
    "PydanticDeprecationWarning",
    "PydanticErrorCodes",
    "PydanticExperimentalWarning",
    "PydanticForbiddenQualifier",
    "PydanticImportError",
    "PydanticInvalidForJsonSchema",
    "PydanticSchemaGenerationError",
    "PydanticUndefinedAnnotation",
    "PydanticUserError",
    "RedisDsn",
    "RootModel",
    "Secret",
    "SecretBytes",
    "SecretStr",
    "SerializationInfo",
    "SerializeAsAny",
    "SerializerFunctionWrapHandler",
    "SkipValidation",
    "SnowflakeDsn",
    "SocketPath",
    "Strict",
    "StrictBool",
    "StrictBytes",
    "StrictFloat",
    "StrictInt",
    "StrictStr",
    "StringConstraints",
    "Tag",
    "TypeAdapter",
    "UUID1",
    "UUID3",
    "UUID4",
    "UUID5",
    "UUID6",
    "UUID7",
    "UUID8",
    "UrlConstraints",
    "VERSION",
    "ValidateAs",
    "ValidationError",
    "ValidationInfo",
    "ValidatorFunctionWrapHandler",
    "WebsocketUrl",
    "WithJsonSchema",
    "WrapSerializer",
    "WrapValidator",
    "__version__",
    "computed_field",
    "conbytes",
    "condate",
    "condecimal",
    "confloat",
    "confrozenset",
    "conint",
    "conlist",
    "conset",
    "constr",
    "create_model",
    "dataclasses",
    "field_serializer",
    "field_validator",
    "model_serializer",
    "model_validator",
    "validate_call",
    "validate_email",
    "with_config",
  ],
  alias_generators: ["to_camel", "to_pascal", "to_snake"],
  aliases: ["AliasChoices", "AliasGenerator", "AliasPath"],
  annotated_handlers: ["GetCoreSchemaHandler", "GetJsonSchemaHandler"],
  color: [
    "Any",
    "COLORS_BY_NAME",
    "COLORS_BY_VALUE",
    "Callable",
    "Color",
    "ColorTuple",
    "ColorType",
    "CoreSchema",
    "HslColorTuple",
    "JsonSchemaValue",
    "Optional",
    "PydanticCustomError",
    "PydanticDeprecatedSince20",
    "RGBA",
    "Union",
    "cast",
    "core_schema",
    "deprecated",
    "float_to_255",
    "hls_to_rgb",
    "ints_to_rgba",
    "math",
    "parse_color_value",
    "parse_float_alpha",
    "parse_hsl",
    "parse_str",
    "parse_tuple",
    "r_hex_long",
    "r_hex_short",
    "r_hsl",
    "r_hsl_v4_style",
    "r_rgb",
    "r_rgb_v4_style",
    "rads",
    "re",
    "repeat_colors",
    "rgb_to_hls",
  ],
  config: ["ConfigDict", "with_config"],
  dataclasses: ["dataclass", "rebuild_dataclass"],
  errors: [
    "PydanticErrorCodes",
    "PydanticForbiddenQualifier",
    "PydanticImportError",
    "PydanticInvalidForJsonSchema",
    "PydanticSchemaGenerationError",
    "PydanticUndefinedAnnotation",
    "PydanticUserError",
  ],
  fields: ["Field", "FieldInfo", "PrivateAttr", "computed_field"],
  functional_serializers: [
    "Annotated",
    "Any",
    "AnyType",
    "Callable",
    "GetCoreSchemaHandler",
    "Literal",
    "PlainSerializer",
    "PydanticUndefined",
    "PydanticUndefinedAnnotation",
    "PydanticUserError",
    "SerializationInfo",
    "SerializeAsAny",
    "SerializerFunctionWrapHandler",
    "TYPE_CHECKING",
    "TypeAlias",
    "TypeVar",
    "WhenUsed",
    "WrapSerializer",
    "annotations",
    "core_schema",
    "dataclasses",
    "field_serializer",
    "model_serializer",
    "overload",
    "partial",
    "partialmethod",
  ],
  functional_validators: [
    "AfterValidator",
    "Annotated",
    "Any",
    "AnyType",
    "ArbitraryTypeWarning",
    "BeforeValidator",
    "Callable",
    "FieldValidatorModes",
    "FreeModelBeforeValidator",
    "FreeModelBeforeValidatorWithoutInfo",
    "GetCoreSchemaHandler",
    "InstanceOf",
    "Literal",
    "ModelAfterValidator",
    "ModelAfterValidatorWithoutInfo",
    "ModelBeforeValidator",
    "ModelBeforeValidatorWithoutInfo",
    "ModelWrapValidator",
    "ModelWrapValidatorHandler",
    "ModelWrapValidatorWithoutInfo",
    "PlainValidator",
    "Protocol",
    "PydanticDeprecatedSince212",
    "PydanticUndefined",
    "PydanticUserError",
    "Self",
    "SkipValidation",
    "TYPE_CHECKING",
    "TypeAlias",
    "TypeVar",
    "Union",
    "ValidateAs",
    "WrapValidator",
    "cast",
    "core_schema",
    "dataclasses",
    "field_validator",
    "model_validator",
    "overload",
    "partialmethod",
    "sys",
    "version_short",
    "warnings",
  ],
  json_schema: [
    "Annotated",
    "Any",
    "AnyType",
    "Callable",
    "ComputedField",
    "CoreModeRef",
    "CoreRef",
    "CoreSchema",
    "CoreSchemaOrFieldType",
    "Counter",
    "DEFAULT_REF_TEMPLATE",
    "DefsRef",
    "Enum",
    "Examples",
    "GenerateJsonSchema",
    "GetJsonSchemaHandler",
    "Hashable",
    "Iterable",
    "JsonDict",
    "JsonRef",
    "JsonSchemaKeyT",
    "JsonSchemaMode",
    "JsonSchemaValue",
    "JsonSchemaWarningKind",
    "JsonValue",
    "Literal",
    "MISSING",
    "NewType",
    "NoDefault",
    "Pattern",
    "PydanticDeprecatedSince26",
    "PydanticDeprecatedSince29",
    "PydanticInvalidForJsonSchema",
    "PydanticJsonSchemaWarning",
    "PydanticOmit",
    "PydanticSchemaGenerationError",
    "PydanticUserError",
    "Sequence",
    "SkipJsonSchema",
    "TYPE_CHECKING",
    "TypeAlias",
    "TypeVar",
    "Union",
    "WithJsonSchema",
    "assert_never",
    "cast",
    "collections",
    "core_schema",
    "dataclasses",
    "deepcopy",
    "defaultdict",
    "deprecated",
    "final",
    "get_literal_values",
    "inspect",
    "math",
    "model_json_schema",
    "models_json_schema",
    "os",
    "overload",
    "pydantic_core",
    "re",
    "to_jsonable_python",
    "warnings",
  ],
  main: ["BaseModel", "create_model"],
  networks: [
    "AmqpDsn",
    "AnyHttpUrl",
    "AnyUrl",
    "AnyWebsocketUrl",
    "ClickHouseDsn",
    "CockroachDsn",
    "EmailStr",
    "FileUrl",
    "FtpUrl",
    "HttpUrl",
    "IPvAnyAddress",
    "IPvAnyInterface",
    "IPvAnyNetwork",
    "KafkaDsn",
    "MariaDBDsn",
    "MongoDsn",
    "MySQLDsn",
    "NameEmail",
    "NatsDsn",
    "PostgresDsn",
    "RedisDsn",
    "SnowflakeDsn",
    "UrlConstraints",
    "WebsocketUrl",
    "validate_email",
  ],
  plugin: [
    "BaseValidateHandlerProtocol",
    "NewSchemaReturns",
    "PydanticPluginProtocol",
    "SchemaKind",
    "SchemaTypePath",
    "ValidateJsonHandlerProtocol",
    "ValidatePythonHandlerProtocol",
    "ValidateStringsHandlerProtocol",
  ],
  root_model: ["RootModel"],
  type_adapter: [
    "Any",
    "BaseModel",
    "Callable",
    "ConfigDict",
    "CoreSchema",
    "DEFAULT_REF_TEMPLATE",
    "ExtraValues",
    "FrameType",
    "GenerateJsonSchema",
    "Generic",
    "IncEx",
    "Iterable",
    "JsonSchemaKeyT",
    "JsonSchemaMode",
    "JsonSchemaValue",
    "Literal",
    "P",
    "ParamSpec",
    "PluggableSchemaValidator",
    "PydanticUndefinedAnnotation",
    "PydanticUserError",
    "R",
    "SchemaSerializer",
    "SchemaValidator",
    "Some",
    "T",
    "TypeAdapter",
    "TypeAdapterT",
    "TypeVar",
    "cast",
    "create_schema_validator",
    "final",
    "is_dataclass",
    "is_typeddict",
    "overload",
    "sys",
    "types",
  ],
  types: [
    "AllowInfNan",
    "AwareDatetime",
    "Base64Bytes",
    "Base64Encoder",
    "Base64Str",
    "Base64UrlBytes",
    "Base64UrlStr",
    "ByteSize",
    "DirectoryPath",
    "Discriminator",
    "EncodedBytes",
    "EncodedStr",
    "EncoderProtocol",
    "FailFast",
    "FilePath",
    "FiniteFloat",
    "FutureDate",
    "FutureDatetime",
    "GetPydanticSchema",
    "ImportString",
    "Json",
    "JsonValue",
    "NaiveDatetime",
    "NegativeFloat",
    "NegativeInt",
    "NewPath",
    "NonNegativeFloat",
    "NonNegativeInt",
    "NonPositiveFloat",
    "NonPositiveInt",
    "OnErrorOmit",
    "PastDate",
    "PastDatetime",
    "PaymentCardNumber",
    "PositiveFloat",
    "PositiveInt",
    "Secret",
    "SecretBytes",
    "SecretStr",
    "SocketPath",
    "Strict",
    "StrictBool",
    "StrictBytes",
    "StrictFloat",
    "StrictInt",
    "StrictStr",
    "StringConstraints",
    "Tag",
    "UUID1",
    "UUID3",
    "UUID4",
    "UUID5",
    "UUID6",
    "UUID7",
    "UUID8",
    "conbytes",
    "condate",
    "condecimal",
    "confloat",
    "confrozenset",
    "conint",
    "conlist",
    "conset",
    "constr",
  ],
  validate_call_decorator: ["validate_call"],
  version: ["VERSION", "version_info"],
  warnings: [
    "ArbitraryTypeWarning",
    "PydanticDeprecatedSince20",
    "PydanticDeprecatedSince210",
    "PydanticDeprecatedSince211",
    "PydanticDeprecatedSince212",
    "PydanticDeprecatedSince26",
    "PydanticDeprecatedSince29",
    "PydanticDeprecationWarning",
    "PydanticExperimentalWarning",
    "TypedDictExtraConfigWarning",
    "UnsupportedFieldAttributeWarning",
  ],
} as const satisfies ModuleDescriptor;

export const pydanticModule = createModule({
  name: "pydantic",
  descriptor: pydanticDescriptor,
});

/** `typing` stdlib symbols used heavily with Pydantic generics and annotations. */
export const typingModule = createModule({
  name: "typing",
  descriptor: {
    ".": [
      "Annotated",
      "Any",
      "ClassVar",
      "Generic",
      "Literal",
      "Optional",
      "Protocol",
      "TypeVar",
      "Union",
      // Class- and method-level decorators commonly stacked above the
      // intrinsic `class` / `def`.
      "final",
      "override",
      "runtime_checkable",
    ],
  },
});

export const pydanticSettingsModule = createModule({
  name: "pydantic_settings",
  descriptor: {
    ".": ["BaseSettings", "SettingsConfigDict"],
  },
});
