// prettier-ignore
import * as core from "@alloy-js/core";
import * as base from "../index.js";

export const AliasDeclaration = core.stc(base.AliasDeclaration);
export const ArrayExpression = core.stc(base.ArrayExpression);
export const ArrayValue = core.stc(base.ArrayValue);
export const AugmentDecorator = core.stc(base.AugmentDecorator);
export const ConstDeclaration = core.stc(base.ConstDeclaration);
export const DecoratorApplication = core.stc(base.DecoratorApplication);
export const DecoratorDeclaration = core.stc(base.DecoratorDeclaration);
export const DeprecatedDirective = core.stc(base.DeprecatedDirective);
export const DocComment = core.stc(base.DocComment);
export const DocParam = core.stc(base.DocParam);
export const DocReturns = core.stc(base.DocReturns);
export const DocTemplate = core.stc(base.DocTemplate);
export const EnumDeclaration = core.stc(base.EnumDeclaration);
export const EnumMember = core.stc(base.EnumMember);
export const ImportStatement = core.stc(base.ImportStatement);
export const InterfaceDeclaration = core.stc(base.InterfaceDeclaration);
export const IntersectionExpression = core.stc(base.IntersectionExpression);
export const ModelDeclaration = core.stc(base.ModelDeclaration);
export const ModelExpression = core.stc(base.ModelExpression);
export const ModelProperty = core.stc(base.ModelProperty);
export const Namespace = core.stc(base.Namespace);
export const ObjectValue = core.stc(base.ObjectValue);
export const ObjectValueProperty = core.stc(base.ObjectValueProperty);
export const OperationDeclaration = core.stc(base.OperationDeclaration);
export const Parameters = core.stc(base.Parameters);
export const Reference = core.stc(base.Reference);
export const ScalarConstructor = core.stc(base.ScalarConstructor);
export const ScalarDeclaration = core.stc(base.ScalarDeclaration);
export const SourceFile = core.stc(base.SourceFile);
export const SpreadExpression = core.stc(base.SpreadExpression);
export const StringLiteral = core.stc(base.StringLiteral);
export const StringTemplateExpr = core.stc(base.StringTemplateExpr);
export const SuppressDirective = core.stc(base.SuppressDirective);
export const TemplateArguments = core.stc(base.TemplateArguments);
export const TemplateParameters = core.stc(base.TemplateParameters);
export const TypeOfExpression = core.stc(base.TypeOfExpression);
export const UnionDeclaration = core.stc(base.UnionDeclaration);
export const UnionExpression = core.stc(base.UnionExpression);
export const UnionVariant = core.stc(base.UnionVariant);
export const UsingStatement = core.stc(base.UsingStatement);
