import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_alloc = {
  Allocator: { kind: "trait", metadata: { since: "unstable" } },
  AllocError: { kind: "struct", metadata: { since: "unstable" } },
  GlobalAlloc: { kind: "trait", metadata: { since: "1.28.0" } },
  Layout: {
    kind: "struct", metadata: { since: "1.28.0" },
    members: {
      adjust_alignment_to: { kind: "function", metadata: { since: "unstable" } },
      align: { kind: "function", metadata: { since: "1.28.0" } },
      align_to: { kind: "function", metadata: { since: "1.44.0" } },
      alignment: { kind: "function", metadata: { since: "unstable" } },
      array: { kind: "function", associated: true, metadata: { since: "1.44.0" } },
      dangling_ptr: { kind: "function", metadata: { since: "1.95.0" } },
      extend: { kind: "function", metadata: { since: "1.44.0" } },
      extend_packed: { kind: "function", metadata: { since: "1.95.0" } },
      for_value: { kind: "function", associated: true, metadata: { since: "1.28.0" } },
      for_value_raw: { kind: "function", associated: true, metadata: { since: "unstable" } },
      from_size_align: { kind: "function", associated: true, metadata: { since: "1.28.0" } },
      from_size_align_unchecked: { kind: "function", associated: true, metadata: { since: "1.28.0" } },
      from_size_alignment: { kind: "function", associated: true, metadata: { since: "unstable" } },
      from_size_alignment_unchecked: { kind: "function", associated: true, metadata: { since: "unstable" } },
      new: { kind: "function", associated: true, metadata: { since: "1.28.0" } },
      pad_to_align: { kind: "function", metadata: { since: "1.44.0" } },
      padding_needed_for: { kind: "function", metadata: { since: "unstable" } },
      repeat: { kind: "function", metadata: { since: "1.95.0" } },
      repeat_packed: { kind: "function", metadata: { since: "1.95.0" } },
      size: { kind: "function", metadata: { since: "1.28.0" } },
    },
  },
  LayoutErr: { kind: "type-alias", metadata: { since: "1.28.0" } },
  LayoutError: { kind: "struct", metadata: { since: "1.50.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
