import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_any = {
  Any: { kind: "trait", metadata: { since: "1.0.0" } },
  try_as_dyn: { kind: "function", metadata: { since: "unstable" } },
  try_as_dyn_mut: { kind: "function", metadata: { since: "unstable" } },
  type_name: { kind: "function", metadata: { since: "1.38.0" } },
  type_name_of_val: { kind: "function", metadata: { since: "1.76.0" } },
  TypeId: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      info: { kind: "function", metadata: { since: "unstable" } },
      of: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      trait_info_of: { kind: "function", metadata: { since: "unstable" } },
      trait_info_of_trait_type_id: { kind: "function", metadata: { since: "unstable" } },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
