import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_borrow = {
  Borrow: { kind: "trait", metadata: { since: "1.0.0" } },
  BorrowMut: { kind: "trait", metadata: { since: "1.0.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
