import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_char_ = {
  CharCase: { kind: "enum", metadata: { since: "unstable" } },
  CharTryFromError: { kind: "struct", metadata: { since: "1.34.0" } },
  decode_utf16: { kind: "function", metadata: { since: "1.9.0" } },
  DecodeUtf16: { kind: "struct", metadata: { since: "1.9.0" } },
  DecodeUtf16Error: {
    kind: "struct", metadata: { since: "1.9.0" },
    members: {
      unpaired_surrogate: { kind: "function", metadata: { since: "1.9.0" } },
    },
  },
  EscapeDebug: { kind: "struct", metadata: { since: "1.20.0" } },
  EscapeDefault: { kind: "struct", metadata: { since: "1.0.0" } },
  EscapeUnicode: { kind: "struct", metadata: { since: "1.0.0" } },
  from_digit: { kind: "function", metadata: { since: "1.0.0" } },
  from_u32: { kind: "function", metadata: { since: "1.0.0" } },
  from_u32_unchecked: { kind: "function", metadata: { since: "1.5.0" } },
  MAX: { kind: "const", metadata: { since: "1.0.0" } },
  MAX_LEN_UTF16: { kind: "const", metadata: { since: "unstable" } },
  MAX_LEN_UTF8: { kind: "const", metadata: { since: "unstable" } },
  ParseCharError: { kind: "struct", metadata: { since: "1.20.0" } },
  REPLACEMENT_CHARACTER: { kind: "const", metadata: { since: "1.9.0" } },
  ToLowercase: { kind: "struct", metadata: { since: "1.0.0" } },
  ToTitlecase: { kind: "struct", metadata: { since: "unstable" } },
  ToUppercase: { kind: "struct", metadata: { since: "1.0.0" } },
  TryFromCharError: { kind: "struct", metadata: { since: "1.59.0" } },
  UNICODE_VERSION: { kind: "const", metadata: { since: "1.45.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
