import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_clone = {
  Clone: { kind: "trait", metadata: { since: "1.0.0" } },
  CloneToUninit: { kind: "trait", metadata: { since: "unstable" } },
  TrivialClone: { kind: "trait", metadata: { since: "unstable" } },
  UseCloned: { kind: "trait", metadata: { since: "unstable" } },
} as const satisfies Record<string, SymbolDescriptor>;
