import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_contracts = {
  build_check_ensures: { kind: "function", metadata: { since: "unstable" } },
} as const satisfies Record<string, SymbolDescriptor>;
