import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_convert = {
  AsMut: { kind: "trait", metadata: { since: "1.0.0" } },
  AsRef: { kind: "trait", metadata: { since: "1.0.0" } },
  FloatToInt: { kind: "trait", metadata: { since: "unstable" } },
  From: { kind: "trait", metadata: { since: "1.0.0" } },
  identity: { kind: "function", metadata: { since: "1.33.0" } },
  Infallible: { kind: "enum", metadata: { since: "1.34.0" } },
  Into: { kind: "trait", metadata: { since: "1.0.0" } },
  TryFrom: { kind: "trait", metadata: { since: "1.34.0" } },
  TryInto: { kind: "trait", metadata: { since: "1.34.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
