import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_f32 = {
  DIGITS: { kind: "const", metadata: { since: "1.0.0" } },
  EPSILON: { kind: "const", metadata: { since: "1.0.0" } },
  INFINITY: { kind: "const", metadata: { since: "1.0.0" } },
  MANTISSA_DIGITS: { kind: "const", metadata: { since: "1.0.0" } },
  MAX: { kind: "const", metadata: { since: "1.0.0" } },
  MAX_10_EXP: { kind: "const", metadata: { since: "1.0.0" } },
  MAX_EXP: { kind: "const", metadata: { since: "1.0.0" } },
  MIN: { kind: "const", metadata: { since: "1.0.0" } },
  MIN_10_EXP: { kind: "const", metadata: { since: "1.0.0" } },
  MIN_EXP: { kind: "const", metadata: { since: "1.0.0" } },
  MIN_POSITIVE: { kind: "const", metadata: { since: "1.0.0" } },
  NAN: { kind: "const", metadata: { since: "1.0.0" } },
  NEG_INFINITY: { kind: "const", metadata: { since: "1.0.0" } },
  RADIX: { kind: "const", metadata: { since: "1.0.0" } },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_f32_consts = {
  E: { kind: "const", metadata: { since: "1.0.0" } },
  EULER_GAMMA: { kind: "const", metadata: { since: "1.94.0" } },
  FRAC_1_PI: { kind: "const", metadata: { since: "1.0.0" } },
  FRAC_1_SQRT_2: { kind: "const", metadata: { since: "1.0.0" } },
  FRAC_1_SQRT_2PI: { kind: "const", metadata: { since: "unstable" } },
  FRAC_1_SQRT_3: { kind: "const", metadata: { since: "unstable" } },
  FRAC_1_SQRT_5: { kind: "const", metadata: { since: "unstable" } },
  FRAC_1_SQRT_PI: { kind: "const", metadata: { since: "unstable" } },
  FRAC_2_PI: { kind: "const", metadata: { since: "1.0.0" } },
  FRAC_2_SQRT_PI: { kind: "const", metadata: { since: "1.0.0" } },
  FRAC_PI_2: { kind: "const", metadata: { since: "1.0.0" } },
  FRAC_PI_3: { kind: "const", metadata: { since: "1.0.0" } },
  FRAC_PI_4: { kind: "const", metadata: { since: "1.0.0" } },
  FRAC_PI_6: { kind: "const", metadata: { since: "1.0.0" } },
  FRAC_PI_8: { kind: "const", metadata: { since: "1.0.0" } },
  GOLDEN_RATIO: { kind: "const", metadata: { since: "1.94.0" } },
  LN_10: { kind: "const", metadata: { since: "1.0.0" } },
  LN_2: { kind: "const", metadata: { since: "1.0.0" } },
  LOG10_2: { kind: "const", metadata: { since: "1.43.0" } },
  LOG10_E: { kind: "const", metadata: { since: "1.0.0" } },
  LOG2_10: { kind: "const", metadata: { since: "1.43.0" } },
  LOG2_E: { kind: "const", metadata: { since: "1.0.0" } },
  PI: { kind: "const", metadata: { since: "1.0.0" } },
  SQRT_2: { kind: "const", metadata: { since: "1.0.0" } },
  SQRT_3: { kind: "const", metadata: { since: "unstable" } },
  SQRT_5: { kind: "const", metadata: { since: "unstable" } },
  TAU: { kind: "const", metadata: { since: "1.47.0" } },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_f32_math = {
  abs_sub: { kind: "function", metadata: { since: "1.0.0" } },
  cbrt: { kind: "function", metadata: { since: "unstable" } },
  ceil: { kind: "function", metadata: { since: "unstable" } },
  div_euclid: { kind: "function", metadata: { since: "unstable" } },
  floor: { kind: "function", metadata: { since: "unstable" } },
  fract: { kind: "function", metadata: { since: "unstable" } },
  mul_add: { kind: "function", metadata: { since: "unstable" } },
  powi: { kind: "function", metadata: { since: "unstable" } },
  rem_euclid: { kind: "function", metadata: { since: "unstable" } },
  round: { kind: "function", metadata: { since: "unstable" } },
  round_ties_even: { kind: "function", metadata: { since: "unstable" } },
  sqrt: { kind: "function", metadata: { since: "unstable" } },
  trunc: { kind: "function", metadata: { since: "unstable" } },
} as const satisfies Record<string, SymbolDescriptor>;
