import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_ffi = {
  c_char: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_double: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_float: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_int: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_long: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_longlong: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_ptrdiff_t: { kind: "type-alias", metadata: { since: "unstable" } },
  c_schar: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_short: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_size_t: { kind: "type-alias", metadata: { since: "unstable" } },
  c_ssize_t: { kind: "type-alias", metadata: { since: "unstable" } },
  c_uchar: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_uint: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_ulong: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_ulonglong: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_ushort: { kind: "type-alias", metadata: { since: "1.64.0" } },
  c_void: { kind: "enum", metadata: { since: "1.30.0" } },
  CStr: {
    kind: "struct", metadata: { since: "1.64.0" },
    members: {
      as_c_str: { kind: "function", metadata: { since: "unstable" } },
      as_ptr: { kind: "function", metadata: { since: "1.0.0" } },
      bytes: { kind: "function", metadata: { since: "unstable" } },
      count_bytes: { kind: "function", metadata: { since: "1.79.0" } },
      display: { kind: "function", metadata: { since: "unstable" } },
      from_bytes_until_nul: { kind: "function", associated: true, metadata: { since: "1.69.0" } },
      from_bytes_with_nul: { kind: "function", associated: true, metadata: { since: "1.10.0" } },
      from_bytes_with_nul_unchecked: { kind: "function", associated: true, metadata: { since: "1.10.0" } },
      from_ptr: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      is_empty: { kind: "function", metadata: { since: "1.71.0" } },
      to_bytes: { kind: "function", metadata: { since: "1.0.0" } },
      to_bytes_with_nul: { kind: "function", metadata: { since: "1.0.0" } },
      to_str: { kind: "function", metadata: { since: "1.4.0" } },
    },
  },
  FromBytesUntilNulError: { kind: "struct", metadata: { since: "1.69.0" } },
  FromBytesWithNulError: { kind: "enum", metadata: { since: "1.64.0" } },
  VaArgSafe: { kind: "trait" },
  VaList: {
    kind: "struct",
    members: {
      arg: { kind: "function", metadata: { since: "unstable" } },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_ffi_c_str = {
  Bytes: { kind: "struct", metadata: { since: "unstable" } },
  CStr: {
    kind: "struct", metadata: { since: "1.64.0" },
    members: {
      as_c_str: { kind: "function", metadata: { since: "unstable" } },
      as_ptr: { kind: "function", metadata: { since: "1.0.0" } },
      bytes: { kind: "function", metadata: { since: "unstable" } },
      count_bytes: { kind: "function", metadata: { since: "1.79.0" } },
      display: { kind: "function", metadata: { since: "unstable" } },
      from_bytes_until_nul: { kind: "function", associated: true, metadata: { since: "1.69.0" } },
      from_bytes_with_nul: { kind: "function", associated: true, metadata: { since: "1.10.0" } },
      from_bytes_with_nul_unchecked: { kind: "function", associated: true, metadata: { since: "1.10.0" } },
      from_ptr: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      is_empty: { kind: "function", metadata: { since: "1.71.0" } },
      to_bytes: { kind: "function", metadata: { since: "1.0.0" } },
      to_bytes_with_nul: { kind: "function", metadata: { since: "1.0.0" } },
      to_str: { kind: "function", metadata: { since: "1.4.0" } },
    },
  },
  FromBytesUntilNulError: { kind: "struct", metadata: { since: "1.69.0" } },
  FromBytesWithNulError: { kind: "enum", metadata: { since: "1.64.0" } },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_ffi_va_list = {
  VaArgSafe: { kind: "trait" },
  VaList: {
    kind: "struct",
    members: {
      arg: { kind: "function", metadata: { since: "unstable" } },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
