import { type SymbolCreator } from "@alloy-js/core";
import {
  type CrateDescriptor,
  type CrateRef,
  createCrate,
  type ExternalCrate,
} from "../../create-crate.js";
import { mod_alloc } from "./alloc.js";
import { mod_any } from "./any.js";
import { mod_array } from "./array.js";
import { mod_ascii } from "./ascii.js";
import { mod_borrow } from "./borrow.js";
import { mod_cell } from "./cell.js";
import { mod_char_ } from "./char.js";
import { mod_clone } from "./clone.js";
import { mod_cmp } from "./cmp.js";
import { mod_contracts } from "./contracts.js";
import { mod_convert } from "./convert.js";
import { mod_default_ } from "./default.js";
import { mod_error } from "./error.js";
import { mod_f32, mod_f32_consts, mod_f32_math } from "./f32.js";
import { mod_f64, mod_f64_consts, mod_f64_math } from "./f64.js";
import { mod_ffi, mod_ffi_c_str, mod_ffi_va_list } from "./ffi.js";
import { mod_fmt } from "./fmt.js";
import { mod_future } from "./future.js";
import { mod_hash } from "./hash.js";
import { mod_io } from "./io.js";
import { mod_iter } from "./iter.js";
import { mod_marker } from "./marker.js";
import { mod_mem, mod_mem_type_info } from "./mem.js";
import { mod_net } from "./net.js";
import { mod_num } from "./num.js";
import { mod_ops } from "./ops.js";
import { mod_option } from "./option.js";
import { mod_panic } from "./panic.js";
import { mod_panicking, mod_panicking_panic_const } from "./panicking.js";
import { mod_pat } from "./pat.js";
import { mod_pin } from "./pin.js";
import { mod_profiling } from "./profiling.js";
import { mod_ptr } from "./ptr.js";
import { mod_random } from "./random.js";
import { mod_range, mod_range_legacy } from "./range.js";
import { mod_result } from "./result.js";
import { mod_root } from "./root.js";
import { mod_slice } from "./slice.js";
import { mod_str, mod_str_pattern } from "./str.js";
import { mod_sync, mod_sync_atomic } from "./sync.js";
import { mod_task } from "./task.js";
import { mod_time } from "./time.js";
import { mod_ub_checks } from "./ub_checks.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

const coreDescriptor = {
  name: "core",
  builtin: true,
  modules: {
    "alloc": mod_alloc,
    "any": mod_any,
    "array": mod_array,
    "ascii": mod_ascii,
    "borrow": mod_borrow,
    "cell": mod_cell,
    "char": mod_char_,
    "clone": mod_clone,
    "cmp": mod_cmp,
    "contracts": mod_contracts,
    "convert": mod_convert,
    "default": mod_default_,
    "error": mod_error,
    "f32": mod_f32,
    "f32::consts": mod_f32_consts,
    "f32::math": mod_f32_math,
    "f64": mod_f64,
    "f64::consts": mod_f64_consts,
    "f64::math": mod_f64_math,
    "ffi": mod_ffi,
    "ffi::c_str": mod_ffi_c_str,
    "ffi::va_list": mod_ffi_va_list,
    "fmt": mod_fmt,
    "future": mod_future,
    "hash": mod_hash,
    "io": mod_io,
    "iter": mod_iter,
    "marker": mod_marker,
    "mem": mod_mem,
    "mem::type_info": mod_mem_type_info,
    "net": mod_net,
    "num": mod_num,
    "ops": mod_ops,
    "option": mod_option,
    "panic": mod_panic,
    "panicking": mod_panicking,
    "panicking::panic_const": mod_panicking_panic_const,
    "pat": mod_pat,
    "pin": mod_pin,
    "profiling": mod_profiling,
    "ptr": mod_ptr,
    "random": mod_random,
    "range": mod_range,
    "range::legacy": mod_range_legacy,
    "result": mod_result,
    "": mod_root,
    "slice": mod_slice,
    "str": mod_str,
    "str::pattern": mod_str_pattern,
    "sync": mod_sync,
    "sync::atomic": mod_sync_atomic,
    "task": mod_task,
    "time": mod_time,
    "ub_checks": mod_ub_checks,
  },
} as const satisfies CrateDescriptor;

/**
 * The `core` crate descriptor.
 */
export type CoreCrate = CrateRef<typeof coreDescriptor> &
  SymbolCreator &
  ExternalCrate;
export const core: CoreCrate = createCrate(coreDescriptor);
