import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_io = {
  BorrowedBuf: {
    kind: "struct",
    members: {
      capacity: { kind: "function" },
      clear: { kind: "function" },
      filled: { kind: "function" },
      filled_mut: { kind: "function" },
      init_len: { kind: "function" },
      into_filled: { kind: "function" },
      into_filled_mut: { kind: "function" },
      len: { kind: "function" },
      set_init: { kind: "function" },
      unfilled: { kind: "function" },
    },
  },
  BorrowedCursor: {
    kind: "struct",
    members: {
      advance: { kind: "function" },
      advance_unchecked: { kind: "function" },
      append: { kind: "function" },
      as_mut: { kind: "function" },
      capacity: { kind: "function" },
      ensure_init: { kind: "function" },
      init_mut: { kind: "function" },
      reborrow: { kind: "function" },
      set_init: { kind: "function" },
      with_unfilled_buf: { kind: "function" },
      written: { kind: "function" },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
