import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_marker = {
  ConstParamTy_: { kind: "trait", metadata: { since: "unstable" } },
  Copy: { kind: "trait", metadata: { since: "1.0.0" } },
  Destruct: { kind: "trait", metadata: { since: "unstable" } },
  DiscriminantKind: { kind: "trait", metadata: { since: "unstable" } },
  FnPtr: { kind: "trait", metadata: { since: "unstable" } },
  Freeze: { kind: "trait", metadata: { since: "unstable" } },
  MetaSized: { kind: "trait", metadata: { since: "unstable" } },
  PhantomContravariant: {
    kind: "struct",
    members: {
      new: { kind: "function", associated: true },
    },
  },
  PhantomContravariantLifetime: {
    kind: "struct",
    members: {
      new: { kind: "function", associated: true },
    },
  },
  PhantomCovariant: {
    kind: "struct",
    members: {
      new: { kind: "function", associated: true },
    },
  },
  PhantomCovariantLifetime: {
    kind: "struct",
    members: {
      new: { kind: "function", associated: true },
    },
  },
  PhantomData: { kind: "struct", metadata: { since: "1.0.0" } },
  PhantomInvariant: {
    kind: "struct",
    members: {
      new: { kind: "function", associated: true },
    },
  },
  PhantomInvariantLifetime: {
    kind: "struct",
    members: {
      new: { kind: "function", associated: true },
    },
  },
  PhantomPinned: { kind: "struct", metadata: { since: "1.33.0" } },
  PointeeSized: { kind: "trait", metadata: { since: "unstable" } },
  Send: { kind: "trait", metadata: { since: "1.0.0" } },
  Sized: { kind: "trait", metadata: { since: "1.0.0" } },
  StructuralPartialEq: { kind: "trait", metadata: { since: "unstable" } },
  Sync: { kind: "trait", metadata: { since: "1.0.0" } },
  Tuple: { kind: "trait", metadata: { since: "unstable" } },
  Unpin: { kind: "trait", metadata: { since: "1.33.0" } },
  UnsafeUnpin: { kind: "trait", metadata: { since: "unstable" } },
  Unsize: { kind: "trait", metadata: { since: "unstable" } },
  variance: { kind: "function" },
  Variance: { kind: "trait" },
} as const satisfies Record<string, SymbolDescriptor>;
