import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_mem = {
  align_of: { kind: "function", metadata: { since: "1.0.0" } },
  align_of_val: { kind: "function", metadata: { since: "1.0.0" } },
  align_of_val_raw: { kind: "function", metadata: { since: "unstable" } },
  Alignment: {
    kind: "struct", metadata: { since: "unstable" },
    members: {
      as_nonzero: { kind: "function", metadata: { since: "unstable" } },
      as_nonzero_usize: { kind: "function", metadata: { since: "unstable" } },
      as_usize: { kind: "function", metadata: { since: "unstable" } },
      log2: { kind: "function", metadata: { since: "unstable" } },
      mask: { kind: "function", metadata: { since: "unstable" } },
      new: { kind: "function", associated: true, metadata: { since: "unstable" } },
      new_unchecked: { kind: "function", associated: true, metadata: { since: "unstable" } },
      of: { kind: "function", associated: true, metadata: { since: "unstable" } },
      of_val: { kind: "function", associated: true, metadata: { since: "unstable" } },
      of_val_raw: { kind: "function", associated: true, metadata: { since: "unstable" } },
    },
  },
  Assume: {
    kind: "struct", metadata: { since: "unstable" },
    members: {
      and: { kind: "function", metadata: { since: "unstable" } },
      but_not: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  conjure_zst: { kind: "function", metadata: { since: "unstable" } },
  copy: { kind: "function", metadata: { since: "unstable" } },
  discriminant: { kind: "function", metadata: { since: "1.21.0" } },
  Discriminant: { kind: "struct", metadata: { since: "1.21.0" } },
  drop: { kind: "function", metadata: { since: "1.0.0" } },
  DropGuard: {
    kind: "struct", metadata: { since: "unstable" },
    members: {
      dismiss: { kind: "function", associated: true, metadata: { since: "unstable" } },
      new: { kind: "function", associated: true, metadata: { since: "unstable" } },
    },
  },
  forget: { kind: "function", metadata: { since: "1.46.0" } },
  forget_unsized: { kind: "function", metadata: { since: "unstable" } },
  ManuallyDrop: {
    kind: "struct", metadata: { since: "1.20.0" },
    members: {
      drop: { kind: "function", associated: true, metadata: { since: "1.20.0" } },
      into_inner: { kind: "function", associated: true, metadata: { since: "1.20.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.20.0" } },
      take: { kind: "function", associated: true, metadata: { since: "1.42.0" } },
    },
  },
  MaybeDangling: {
    kind: "struct",
    members: {
      as_mut: { kind: "function" },
      as_ref: { kind: "function" },
      into_inner: { kind: "function" },
      new: { kind: "function", associated: true },
    },
  },
  min_align_of: { kind: "function", metadata: { since: "1.0.0" } },
  min_align_of_val: { kind: "function", metadata: { since: "1.0.0" } },
  needs_drop: { kind: "function", metadata: { since: "1.21.0" } },
  offset_of: { kind: "symbol", metadata: { since: "1.77.0" } },
  replace: { kind: "function", metadata: { since: "1.0.0" } },
  size_of: { kind: "function", metadata: { since: "1.0.0" } },
  size_of_val: { kind: "function", metadata: { since: "1.0.0" } },
  size_of_val_raw: { kind: "function", metadata: { since: "unstable" } },
  swap: { kind: "function", metadata: { since: "1.0.0" } },
  take: { kind: "function", metadata: { since: "1.40.0" } },
  transmute: { kind: "function", metadata: { since: "1.0.0" } },
  transmute_copy: { kind: "function", metadata: { since: "1.0.0" } },
  TransmuteFrom: { kind: "trait", metadata: { since: "unstable" } },
  uninitialized: { kind: "function", metadata: { since: "1.0.0" } },
  variant_count: { kind: "function", metadata: { since: "unstable" } },
  zeroed: { kind: "function", metadata: { since: "1.0.0" } },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_mem_type_info = {
  Abi: { kind: "enum", metadata: { since: "unstable" } },
  Array: { kind: "struct", metadata: { since: "unstable" } },
  Bool: { kind: "struct", metadata: { since: "unstable" } },
  Char: { kind: "struct", metadata: { since: "unstable" } },
  Const: { kind: "struct", metadata: { since: "unstable" } },
  DynTrait: { kind: "struct", metadata: { since: "unstable" } },
  DynTraitPredicate: { kind: "struct", metadata: { since: "unstable" } },
  Enum: { kind: "struct", metadata: { since: "unstable" } },
  Field: { kind: "struct", metadata: { since: "unstable" } },
  Float: { kind: "struct", metadata: { since: "unstable" } },
  FnPtr: { kind: "struct", metadata: { since: "unstable" } },
  Generic: { kind: "enum", metadata: { since: "unstable" } },
  GenericType: { kind: "struct", metadata: { since: "unstable" } },
  Int: { kind: "struct", metadata: { since: "unstable" } },
  Lifetime: { kind: "struct", metadata: { since: "unstable" } },
  Pointer: { kind: "struct", metadata: { since: "unstable" } },
  Reference: { kind: "struct", metadata: { since: "unstable" } },
  Slice: { kind: "struct", metadata: { since: "unstable" } },
  Str: { kind: "struct", metadata: { since: "unstable" } },
  Struct: { kind: "struct", metadata: { since: "unstable" } },
  Trait: { kind: "struct", metadata: { since: "unstable" } },
  TraitImpl: {
    kind: "struct", metadata: { since: "unstable" },
    members: {
      get_vtable: { kind: "function" },
    },
  },
  Tuple: { kind: "struct", metadata: { since: "unstable" } },
  Type: {
    kind: "struct", metadata: { since: "unstable" },
    members: {
      of: { kind: "function", associated: true, metadata: { since: "unstable" } },
    },
  },
  TypeKind: { kind: "enum", metadata: { since: "unstable" } },
  Union: { kind: "struct", metadata: { since: "unstable" } },
  Variant: { kind: "struct", metadata: { since: "unstable" } },
} as const satisfies Record<string, SymbolDescriptor>;
