import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_panic = {
  abort_unwind: { kind: "function", metadata: { since: "unstable" } },
  AssertUnwindSafe: { kind: "struct", metadata: { since: "1.9.0" } },
  Location: {
    kind: "struct", metadata: { since: "1.10.0" },
    members: {
      caller: { kind: "function", associated: true, metadata: { since: "1.46.0" } },
      column: { kind: "function", metadata: { since: "1.25.0" } },
      file: { kind: "function", metadata: { since: "1.10.0" } },
      file_as_c_str: { kind: "function", metadata: { since: "1.92.0" } },
      line: { kind: "function", metadata: { since: "1.10.0" } },
    },
  },
  PanicInfo: {
    kind: "struct", metadata: { since: "1.10.0" },
    members: {
      can_unwind: { kind: "function", metadata: { since: "unstable" } },
      location: { kind: "function", metadata: { since: "1.10.0" } },
      message: { kind: "function", metadata: { since: "1.81.0" } },
      payload: { kind: "function", metadata: { since: "1.10.0" } },
    },
  },
  PanicMessage: {
    kind: "struct", metadata: { since: "1.81.0" },
    members: {
      as_str: { kind: "function", metadata: { since: "1.81.0" } },
    },
  },
  RefUnwindSafe: { kind: "trait", metadata: { since: "1.9.0" } },
  UnwindSafe: { kind: "trait", metadata: { since: "1.9.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
