import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_pin = {
  pin: { kind: "symbol", metadata: { since: "1.68.0" } },
  Pin: {
    kind: "struct", metadata: { since: "1.33.0" },
    members: {
      as_deref_mut: { kind: "function", metadata: { since: "1.84.0" } },
      as_mut: { kind: "function", metadata: { since: "1.33.0" } },
      as_ref: { kind: "function", metadata: { since: "1.33.0" } },
      get_mut: { kind: "function", metadata: { since: "1.33.0" } },
      get_ref: { kind: "function", metadata: { since: "1.84.0" } },
      get_unchecked_mut: { kind: "function", metadata: { since: "1.33.0" } },
      into_inner: { kind: "function", associated: true, metadata: { since: "unstable" } },
      into_inner_unchecked: { kind: "function", associated: true, metadata: { since: "unstable" } },
      into_ref: { kind: "function", metadata: { since: "1.84.0" } },
      map_unchecked: { kind: "function", metadata: { since: "1.33.0" } },
      map_unchecked_mut: { kind: "function", metadata: { since: "1.33.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.84.0" } },
      new_unchecked: { kind: "function", associated: true, metadata: { since: "1.84.0" } },
      set: { kind: "function", metadata: { since: "1.33.0" } },
      static_mut: { kind: "function", associated: true, metadata: { since: "1.61.0" } },
      static_ref: { kind: "function", associated: true, metadata: { since: "1.61.0" } },
    },
  },
  PinCoerceUnsized: { kind: "trait", metadata: { since: "unstable" } },
  UnsafePinned: {
    kind: "struct", metadata: { since: "unstable" },
    members: {
      get: { kind: "function", metadata: { since: "unstable" } },
      get_mut_pinned: { kind: "function", metadata: { since: "unstable" } },
      get_mut_unchecked: { kind: "function", metadata: { since: "unstable" } },
      into_inner: { kind: "function", metadata: { since: "unstable" } },
      new: { kind: "function", associated: true, metadata: { since: "unstable" } },
      raw_get: { kind: "function", associated: true, metadata: { since: "unstable" } },
      raw_get_mut: { kind: "function", associated: true, metadata: { since: "unstable" } },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
