import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_slice = {
  ArrayWindows: { kind: "struct", metadata: { since: "1.94.0" } },
  ChunkBy: { kind: "struct", metadata: { since: "1.77.0" } },
  ChunkByMut: { kind: "struct", metadata: { since: "1.77.0" } },
  Chunks: { kind: "struct", metadata: { since: "1.0.0" } },
  ChunksExact: {
    kind: "struct", metadata: { since: "1.31.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "1.31.0" } },
    },
  },
  ChunksExactMut: {
    kind: "struct", metadata: { since: "1.31.0" },
    members: {
      into_remainder: { kind: "function", metadata: { since: "1.31.0" } },
    },
  },
  ChunksMut: { kind: "struct", metadata: { since: "1.0.0" } },
  EscapeAscii: { kind: "struct", metadata: { since: "1.60.0" } },
  from_mut: { kind: "function", metadata: { since: "1.28.0" } },
  from_mut_ptr_range: { kind: "function", metadata: { since: "unstable" } },
  from_ptr_range: { kind: "function", metadata: { since: "unstable" } },
  from_raw_parts: { kind: "function", metadata: { since: "1.0.0" } },
  from_raw_parts_mut: { kind: "function", metadata: { since: "1.0.0" } },
  from_ref: { kind: "function", metadata: { since: "1.28.0" } },
  GetDisjointMutError: { kind: "enum", metadata: { since: "1.86.0" } },
  GetDisjointMutIndex: { kind: "trait", metadata: { since: "unstable" } },
  Iter: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      as_slice: { kind: "function", metadata: { since: "1.4.0" } },
    },
  },
  IterMut: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      as_mut_slice: { kind: "function", metadata: { since: "unstable" } },
      as_slice: { kind: "function", metadata: { since: "1.53.0" } },
      into_slice: { kind: "function", metadata: { since: "1.4.0" } },
    },
  },
  range: { kind: "function", metadata: { since: "unstable" } },
  RChunks: { kind: "struct", metadata: { since: "1.31.0" } },
  RChunksExact: {
    kind: "struct", metadata: { since: "1.31.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "1.31.0" } },
    },
  },
  RChunksExactMut: {
    kind: "struct", metadata: { since: "1.31.0" },
    members: {
      into_remainder: { kind: "function", metadata: { since: "1.31.0" } },
    },
  },
  RChunksMut: { kind: "struct", metadata: { since: "1.31.0" } },
  RSplit: { kind: "struct", metadata: { since: "1.27.0" } },
  RSplitMut: { kind: "struct", metadata: { since: "1.27.0" } },
  RSplitN: { kind: "struct", metadata: { since: "1.0.0" } },
  RSplitNMut: { kind: "struct", metadata: { since: "1.0.0" } },
  SliceIndex: { kind: "trait", metadata: { since: "1.28.0" } },
  SlicePattern: { kind: "trait", metadata: { since: "unstable" } },
  Split: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      as_slice: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  SplitInclusive: { kind: "struct", metadata: { since: "1.51.0" } },
  SplitInclusiveMut: { kind: "struct", metadata: { since: "1.51.0" } },
  SplitMut: { kind: "struct", metadata: { since: "1.0.0" } },
  SplitN: { kind: "struct", metadata: { since: "1.0.0" } },
  SplitNMut: { kind: "struct", metadata: { since: "1.0.0" } },
  try_range: { kind: "function", metadata: { since: "unstable" } },
  Windows: { kind: "struct", metadata: { since: "1.0.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
