import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_ub_checks = {
  assert_unsafe_precondition: { kind: "symbol", metadata: { since: "unstable" } },
  check_library_ub: { kind: "function" },
} as const satisfies Record<string, SymbolDescriptor>;
