import * as core from "@alloy-js/core";
import * as base from "../index.js";

export const Annotation = core.stc(base.Annotation);
export const ArgumentList = core.stc(base.ArgumentList);
export const Class = core.stc(base.Class);
export const Constructor = core.stc(base.Constructor);
export const Declaration = core.stc(base.Declaration);
export const Enum = core.stc(base.Enum);
export const ExtendsClause = core.stc(base.ExtendsClause);
export const ImplementsClause = core.stc(base.ImplementsClause);
export const TypeArguments = core.stc(base.TypeArguments);
export const EnumMember = core.stc(base.EnumMember);
export const ImportStatement = core.stc(base.ImportStatement);
export const Interface = core.stc(base.Interface);
export const MavenProject = core.stc(base.MavenProject);
export const Method = core.stc(base.Method);
export const Modifiers = core.stc(base.Modifiers);
export const Name = core.stc(base.Name);
export const ObjectDeclaration = core.stc(base.ObjectDeclaration);
export const PackageDirectory = core.stc(base.PackageDirectory);
export const Parameters = core.stc(base.Parameters);
export const ProjectDirectory = core.stc(base.ProjectDirectory);
export const Reference = core.stc(base.Reference);
export const SourceFile = core.stc(base.SourceFile);
export const Value = core.stc(base.Value);
export const Variable = core.stc(base.Variable);
export const TypeParameters = core.stc(base.TypeParameters);
export const NamedArgumentList = core.stc(base.NamedArgumentList);
