import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_array = {
  from_fn: { kind: "function", metadata: { since: "1.63.0" } },
  from_mut: { kind: "function", metadata: { since: "1.53.0" } },
  from_ref: { kind: "function", metadata: { since: "1.53.0" } },
  Guard: { kind: "struct" },
  IntoIter: {
    kind: "struct", metadata: { since: "1.51.0" },
    members: {
      as_mut_slice: { kind: "function", metadata: { since: "1.51.0" } },
      as_slice: { kind: "function", metadata: { since: "1.51.0" } },
      empty: { kind: "function", associated: true, metadata: { since: "unstable" } },
      new: { kind: "function", associated: true, metadata: { since: "1.51.0" } },
      new_unchecked: { kind: "function", associated: true, metadata: { since: "unstable" } },
    },
  },
  repeat: { kind: "function", metadata: { since: "1.91.0" } },
  try_from_fn: { kind: "function", metadata: { since: "unstable" } },
  TryFromSliceError: { kind: "struct" },
} as const satisfies Record<string, SymbolDescriptor>;
