import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_ascii = {
  AsciiExt: { kind: "trait", metadata: { since: "1.0.0" } },
  Char: {
    kind: "enum",
    members: {
      as_str: { kind: "function", metadata: { since: "unstable" } },
      digit: { kind: "function", associated: true, metadata: { since: "unstable" } },
      digit_unchecked: { kind: "function", associated: true, metadata: { since: "unstable" } },
      eq_ignore_case: { kind: "function", metadata: { since: "unstable" } },
      escape_ascii: { kind: "function", metadata: { since: "unstable" } },
      from_u8: { kind: "function", associated: true, metadata: { since: "unstable" } },
      from_u8_unchecked: { kind: "function", associated: true, metadata: { since: "unstable" } },
      is_alphabetic: { kind: "function", metadata: { since: "unstable" } },
      is_alphanumeric: { kind: "function", metadata: { since: "unstable" } },
      is_control: { kind: "function", metadata: { since: "unstable" } },
      is_digit: { kind: "function", metadata: { since: "unstable" } },
      is_graphic: { kind: "function", metadata: { since: "unstable" } },
      is_hexdigit: { kind: "function", metadata: { since: "unstable" } },
      is_lowercase: { kind: "function", metadata: { since: "unstable" } },
      is_octdigit: { kind: "function", metadata: { since: "unstable" } },
      is_punctuation: { kind: "function", metadata: { since: "unstable" } },
      is_uppercase: { kind: "function", metadata: { since: "unstable" } },
      is_whitespace: { kind: "function", metadata: { since: "unstable" } },
      make_lowercase: { kind: "function", metadata: { since: "unstable" } },
      make_uppercase: { kind: "function", metadata: { since: "unstable" } },
      to_char: { kind: "function", metadata: { since: "unstable" } },
      to_lowercase: { kind: "function", metadata: { since: "unstable" } },
      to_u8: { kind: "function", metadata: { since: "unstable" } },
      to_uppercase: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  escape_default: { kind: "function" },
  EscapeDefault: { kind: "struct" },
} as const satisfies Record<string, SymbolDescriptor>;
