import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_backtrace = {
  Backtrace: {
    kind: "struct", metadata: { since: "1.65.0" },
    members: {
      capture: { kind: "function", associated: true, metadata: { since: "1.65.0" } },
      disabled: { kind: "function", associated: true, metadata: { since: "1.65.0" } },
      force_capture: { kind: "function", associated: true, metadata: { since: "1.65.0" } },
      frames: { kind: "function", metadata: { since: "unstable" } },
      status: { kind: "function", metadata: { since: "1.65.0" } },
    },
  },
  BacktraceFrame: { kind: "struct", metadata: { since: "unstable" } },
  BacktraceStatus: { kind: "enum", metadata: { since: "1.65.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
