import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_borrow = {
  Borrow: { kind: "trait" },
  BorrowMut: { kind: "trait" },
  Cow: {
    kind: "enum",
    members: {
      into_owned: { kind: "function", metadata: { since: "1.0.0" } },
      is_borrowed: { kind: "function", associated: true, metadata: { since: "unstable" } },
      is_owned: { kind: "function", associated: true, metadata: { since: "unstable" } },
      to_mut: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  ToOwned: { kind: "trait" },
} as const satisfies Record<string, SymbolDescriptor>;
