import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_clone = {
  Clone: { kind: "trait" },
  CloneToUninit: { kind: "trait" },
  TrivialClone: { kind: "trait" },
  UseCloned: { kind: "trait" },
} as const satisfies Record<string, SymbolDescriptor>;
