import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_cmp = {
  Eq: { kind: "trait" },
  max: { kind: "function", metadata: { since: "1.0.0" } },
  max_by: { kind: "function", metadata: { since: "1.53.0" } },
  max_by_key: { kind: "function", metadata: { since: "1.53.0" } },
  min: { kind: "function" },
  min_by: { kind: "function", metadata: { since: "1.53.0" } },
  min_by_key: { kind: "function", metadata: { since: "1.53.0" } },
  minmax: { kind: "function", metadata: { since: "unstable" } },
  minmax_by: { kind: "function", metadata: { since: "unstable" } },
  minmax_by_key: { kind: "function", metadata: { since: "unstable" } },
  Ord: { kind: "trait" },
  Ordering: {
    kind: "enum",
    members: {
      is_eq: { kind: "function", metadata: { since: "1.53.0" } },
      is_ge: { kind: "function", metadata: { since: "1.53.0" } },
      is_gt: { kind: "function", metadata: { since: "1.53.0" } },
      is_le: { kind: "function", metadata: { since: "1.53.0" } },
      is_lt: { kind: "function", metadata: { since: "1.53.0" } },
      is_ne: { kind: "function", metadata: { since: "1.53.0" } },
      reverse: { kind: "function", metadata: { since: "1.48.0" } },
      then: { kind: "function", metadata: { since: "1.48.0" } },
      then_with: { kind: "function", metadata: { since: "1.17.0" } },
    },
  },
  PartialEq: { kind: "trait" },
  PartialOrd: { kind: "trait" },
  Reverse: { kind: "struct" },
} as const satisfies Record<string, SymbolDescriptor>;
