import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_default_ = {
  Default: { kind: "trait" },
} as const satisfies Record<string, SymbolDescriptor>;
