import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_env = {
  args: { kind: "function", metadata: { since: "1.0.0" } },
  Args: { kind: "struct", metadata: { since: "1.0.0" } },
  args_os: { kind: "function", metadata: { since: "1.0.0" } },
  ArgsOs: { kind: "struct", metadata: { since: "1.0.0" } },
  current_dir: { kind: "function", metadata: { since: "1.0.0" } },
  current_exe: { kind: "function", metadata: { since: "1.0.0" } },
  home_dir: { kind: "function", metadata: { since: "1.0.0" } },
  join_paths: { kind: "function", metadata: { since: "1.0.0" } },
  JoinPathsError: { kind: "struct", metadata: { since: "1.0.0" } },
  remove_var: { kind: "function", metadata: { since: "1.0.0" } },
  set_current_dir: { kind: "function", metadata: { since: "1.0.0" } },
  set_var: { kind: "function", metadata: { since: "1.0.0" } },
  split_paths: { kind: "function", metadata: { since: "1.0.0" } },
  SplitPaths: { kind: "struct", metadata: { since: "1.0.0" } },
  temp_dir: { kind: "function", metadata: { since: "1.0.0" } },
  var: { kind: "function", metadata: { since: "1.0.0" } },
  var_os: { kind: "function", metadata: { since: "1.0.0" } },
  VarError: { kind: "enum", metadata: { since: "1.0.0" } },
  vars: { kind: "function", metadata: { since: "1.0.0" } },
  Vars: { kind: "struct", metadata: { since: "1.0.0" } },
  vars_os: { kind: "function", metadata: { since: "1.0.0" } },
  VarsOs: { kind: "struct", metadata: { since: "1.0.0" } },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_env_consts = {
  ARCH: { kind: "const", metadata: { since: "1.0.0" } },
  DLL_EXTENSION: { kind: "const", metadata: { since: "1.0.0" } },
  DLL_PREFIX: { kind: "const", metadata: { since: "1.0.0" } },
  DLL_SUFFIX: { kind: "const", metadata: { since: "1.0.0" } },
  EXE_EXTENSION: { kind: "const", metadata: { since: "1.0.0" } },
  EXE_SUFFIX: { kind: "const", metadata: { since: "1.0.0" } },
  FAMILY: { kind: "const", metadata: { since: "1.0.0" } },
  OS: { kind: "const", metadata: { since: "1.0.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
