import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_fs = {
  canonicalize: { kind: "function", metadata: { since: "1.5.0" } },
  copy: { kind: "function", metadata: { since: "1.0.0" } },
  create_dir: { kind: "function", metadata: { since: "1.0.0" } },
  create_dir_all: { kind: "function", metadata: { since: "1.0.0" } },
  Dir: {
    kind: "struct", metadata: { since: "unstable" },
    members: {
      open: { kind: "function", associated: true, metadata: { since: "unstable" } },
      open_file: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  DirBuilder: {
    kind: "struct", metadata: { since: "1.6.0" },
    members: {
      create: { kind: "function", metadata: { since: "1.6.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.6.0" } },
      recursive: { kind: "function", metadata: { since: "1.6.0" } },
    },
  },
  DirEntry: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      file_name: { kind: "function", metadata: { since: "1.1.0" } },
      file_type: { kind: "function", metadata: { since: "1.1.0" } },
      metadata: { kind: "function", metadata: { since: "1.1.0" } },
      path: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  exists: { kind: "function", metadata: { since: "1.81.0" } },
  File: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      create: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      create_buffered: { kind: "function", associated: true, metadata: { since: "unstable" } },
      create_new: { kind: "function", associated: true, metadata: { since: "1.77.0" } },
      lock: { kind: "function", metadata: { since: "1.89.0" } },
      lock_shared: { kind: "function", metadata: { since: "1.89.0" } },
      metadata: { kind: "function", metadata: { since: "1.0.0" } },
      open: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      open_buffered: { kind: "function", associated: true, metadata: { since: "unstable" } },
      options: { kind: "function", associated: true, metadata: { since: "1.58.0" } },
      set_len: { kind: "function", metadata: { since: "1.0.0" } },
      set_modified: { kind: "function", metadata: { since: "1.75.0" } },
      set_permissions: { kind: "function", metadata: { since: "1.16.0" } },
      set_times: { kind: "function", metadata: { since: "1.75.0" } },
      sync_all: { kind: "function", metadata: { since: "1.0.0" } },
      sync_data: { kind: "function", metadata: { since: "1.0.0" } },
      try_clone: { kind: "function", metadata: { since: "1.9.0" } },
      try_lock: { kind: "function", metadata: { since: "1.89.0" } },
      try_lock_shared: { kind: "function", metadata: { since: "1.89.0" } },
      unlock: { kind: "function", metadata: { since: "1.89.0" } },
    },
  },
  FileTimes: {
    kind: "struct", metadata: { since: "1.75.0" },
    members: {
      new: { kind: "function", associated: true, metadata: { since: "1.75.0" } },
      set_accessed: { kind: "function", metadata: { since: "1.75.0" } },
      set_modified: { kind: "function", metadata: { since: "1.75.0" } },
    },
  },
  FileType: {
    kind: "struct", metadata: { since: "1.1.0" },
    members: {
      is_dir: { kind: "function", metadata: { since: "1.1.0" } },
      is_file: { kind: "function", metadata: { since: "1.1.0" } },
      is_symlink: { kind: "function", metadata: { since: "1.1.0" } },
    },
  },
  hard_link: { kind: "function", metadata: { since: "1.0.0" } },
  metadata: { kind: "function", metadata: { since: "1.0.0" } },
  Metadata: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      accessed: { kind: "function", metadata: { since: "1.10.0" } },
      created: { kind: "function", metadata: { since: "1.10.0" } },
      file_type: { kind: "function", metadata: { since: "1.1.0" } },
      is_dir: { kind: "function", metadata: { since: "1.0.0" } },
      is_file: { kind: "function", metadata: { since: "1.0.0" } },
      is_symlink: { kind: "function", metadata: { since: "1.58.0" } },
      len: { kind: "function", metadata: { since: "1.0.0" } },
      modified: { kind: "function", metadata: { since: "1.10.0" } },
      permissions: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  OpenOptions: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      append: { kind: "function", metadata: { since: "1.0.0" } },
      create: { kind: "function", metadata: { since: "1.0.0" } },
      create_new: { kind: "function", metadata: { since: "1.9.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      open: { kind: "function", metadata: { since: "1.0.0" } },
      read: { kind: "function", metadata: { since: "1.0.0" } },
      truncate: { kind: "function", metadata: { since: "1.0.0" } },
      write: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  Permissions: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      readonly: { kind: "function", metadata: { since: "1.0.0" } },
      set_readonly: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  read: { kind: "function", metadata: { since: "1.26.0" } },
  read_dir: { kind: "function", metadata: { since: "1.0.0" } },
  read_link: { kind: "function", metadata: { since: "1.0.0" } },
  read_to_string: { kind: "function", metadata: { since: "1.26.0" } },
  ReadDir: { kind: "struct", metadata: { since: "1.0.0" } },
  remove_dir: { kind: "function", metadata: { since: "1.0.0" } },
  remove_dir_all: { kind: "function", metadata: { since: "1.0.0" } },
  remove_file: { kind: "function", metadata: { since: "1.0.0" } },
  rename: { kind: "function", metadata: { since: "1.0.0" } },
  set_permissions: { kind: "function", metadata: { since: "1.1.0" } },
  set_permissions_nofollow: { kind: "function", metadata: { since: "unstable" } },
  set_times: { kind: "function", metadata: { since: "unstable" } },
  set_times_nofollow: { kind: "function", metadata: { since: "unstable" } },
  soft_link: { kind: "function", metadata: { since: "1.0.0" } },
  symlink_metadata: { kind: "function", metadata: { since: "1.1.0" } },
  TryLockError: { kind: "enum", metadata: { since: "1.89.0" } },
  write: { kind: "function", metadata: { since: "1.26.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
