import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_future = {
  async_drop_in_place: { kind: "function", metadata: { since: "unstable" } },
  AsyncDrop: { kind: "trait", metadata: { since: "unstable" } },
  Future: { kind: "trait", metadata: { since: "1.36.0" } },
  IntoFuture: { kind: "trait", metadata: { since: "1.64.0" } },
  join: { kind: "symbol", metadata: { since: "unstable" } },
  pending: { kind: "function", metadata: { since: "1.48.0" } },
  Pending: { kind: "struct", metadata: { since: "1.48.0" } },
  poll_fn: { kind: "function", metadata: { since: "1.64.0" } },
  PollFn: { kind: "struct", metadata: { since: "1.64.0" } },
  ready: { kind: "function", metadata: { since: "1.48.0" } },
  Ready: {
    kind: "struct", metadata: { since: "1.48.0" },
    members: {
      into_inner: { kind: "function", metadata: { since: "1.82.0" } },
    },
  },
  ResumeTy: { kind: "struct" },
} as const satisfies Record<string, SymbolDescriptor>;
