import { type SymbolCreator } from "@alloy-js/core";
import {
  type CrateDescriptor,
  type CrateRef,
  createCrate,
  type ExternalCrate,
} from "../../create-crate.js";
import { mod_alloc } from "./alloc.js";
import { mod_any } from "./any.js";
import { mod_array } from "./array.js";
import { mod_ascii } from "./ascii.js";
import { mod_backtrace } from "./backtrace.js";
import { mod_borrow } from "./borrow.js";
import { mod_boxed } from "./boxed.js";
import { mod_cell } from "./cell.js";
import { mod_char_ } from "./char.js";
import { mod_clone } from "./clone.js";
import { mod_cmp } from "./cmp.js";
import { mod_collections, mod_collections_binary_heap, mod_collections_hash_map, mod_collections_linked_list, mod_collections_vec_deque } from "./collections.js";
import { mod_contracts } from "./contracts.js";
import { mod_convert } from "./convert.js";
import { mod_default_ } from "./default.js";
import { mod_env, mod_env_consts } from "./env.js";
import { mod_error } from "./error.js";
import { mod_f32, mod_f32_consts, mod_f32_math } from "./f32.js";
import { mod_f64, mod_f64_consts, mod_f64_math } from "./f64.js";
import { mod_ffi, mod_ffi_c_str, mod_ffi_os_str, mod_ffi_va_list } from "./ffi.js";
import { mod_fmt } from "./fmt.js";
import { mod_fs } from "./fs.js";
import { mod_future } from "./future.js";
import { mod_hash } from "./hash.js";
import { mod_io, mod_io_prelude } from "./io.js";
import { mod_iter } from "./iter.js";
import { mod_marker } from "./marker.js";
import { mod_mem, mod_mem_type_info } from "./mem.js";
import { mod_net } from "./net.js";
import { mod_num } from "./num.js";
import { mod_ops } from "./ops.js";
import { mod_option } from "./option.js";
import { mod_panic } from "./panic.js";
import { mod_panicking, mod_panicking_panic_const } from "./panicking.js";
import { mod_pat } from "./pat.js";
import { mod_path } from "./path.js";
import { mod_pin } from "./pin.js";
import { mod_process } from "./process.js";
import { mod_profiling } from "./profiling.js";
import { mod_ptr } from "./ptr.js";
import { mod_random } from "./random.js";
import { mod_range, mod_range_legacy } from "./range.js";
import { mod_rc } from "./rc.js";
import { mod_result } from "./result.js";
import { mod_root } from "./root.js";
import { mod_slice } from "./slice.js";
import { mod_str, mod_str_pattern } from "./str.js";
import { mod_string } from "./string.js";
import { mod_sync, mod_sync_atomic, mod_sync_mpmc, mod_sync_mpsc, mod_sync_nonpoison, mod_sync_oneshot, mod_sync_poison } from "./sync.js";
import { mod_task } from "./task.js";
import { mod_thread } from "./thread.js";
import { mod_time } from "./time.js";
import { mod_ub_checks } from "./ub_checks.js";
import { mod_vec } from "./vec.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

const stdDescriptor = {
  name: "std",
  builtin: true,
  modules: {
    "alloc": mod_alloc,
    "any": mod_any,
    "array": mod_array,
    "ascii": mod_ascii,
    "backtrace": mod_backtrace,
    "borrow": mod_borrow,
    "boxed": mod_boxed,
    "cell": mod_cell,
    "char": mod_char_,
    "clone": mod_clone,
    "cmp": mod_cmp,
    "collections": mod_collections,
    "collections::binary_heap": mod_collections_binary_heap,
    "collections::hash_map": mod_collections_hash_map,
    "collections::linked_list": mod_collections_linked_list,
    "collections::vec_deque": mod_collections_vec_deque,
    "contracts": mod_contracts,
    "convert": mod_convert,
    "default": mod_default_,
    "env": mod_env,
    "env::consts": mod_env_consts,
    "error": mod_error,
    "f32": mod_f32,
    "f32::consts": mod_f32_consts,
    "f32::math": mod_f32_math,
    "f64": mod_f64,
    "f64::consts": mod_f64_consts,
    "f64::math": mod_f64_math,
    "ffi": mod_ffi,
    "ffi::c_str": mod_ffi_c_str,
    "ffi::os_str": mod_ffi_os_str,
    "ffi::va_list": mod_ffi_va_list,
    "fmt": mod_fmt,
    "fs": mod_fs,
    "future": mod_future,
    "hash": mod_hash,
    "io": mod_io,
    "io::prelude": mod_io_prelude,
    "iter": mod_iter,
    "marker": mod_marker,
    "mem": mod_mem,
    "mem::type_info": mod_mem_type_info,
    "net": mod_net,
    "num": mod_num,
    "ops": mod_ops,
    "option": mod_option,
    "panic": mod_panic,
    "panicking": mod_panicking,
    "panicking::panic_const": mod_panicking_panic_const,
    "pat": mod_pat,
    "path": mod_path,
    "pin": mod_pin,
    "process": mod_process,
    "profiling": mod_profiling,
    "ptr": mod_ptr,
    "random": mod_random,
    "range": mod_range,
    "range::legacy": mod_range_legacy,
    "rc": mod_rc,
    "result": mod_result,
    "": mod_root,
    "slice": mod_slice,
    "str": mod_str,
    "str::pattern": mod_str_pattern,
    "string": mod_string,
    "sync": mod_sync,
    "sync::atomic": mod_sync_atomic,
    "sync::mpmc": mod_sync_mpmc,
    "sync::mpsc": mod_sync_mpsc,
    "sync::nonpoison": mod_sync_nonpoison,
    "sync::oneshot": mod_sync_oneshot,
    "sync::poison": mod_sync_poison,
    "task": mod_task,
    "thread": mod_thread,
    "time": mod_time,
    "ub_checks": mod_ub_checks,
    "vec": mod_vec,
  },
} as const satisfies CrateDescriptor;

/**
 * The `std` crate descriptor.
 */
export type StdCrate = CrateRef<typeof stdDescriptor> &
  SymbolCreator &
  ExternalCrate;
export const std: StdCrate = createCrate(stdDescriptor);
