import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_io = {
  BorrowedBuf: {
    kind: "struct",
    members: {
      capacity: { kind: "function" },
      clear: { kind: "function" },
      filled: { kind: "function" },
      filled_mut: { kind: "function" },
      init_len: { kind: "function" },
      into_filled: { kind: "function" },
      into_filled_mut: { kind: "function" },
      len: { kind: "function" },
      set_init: { kind: "function" },
      unfilled: { kind: "function" },
    },
  },
  BorrowedCursor: {
    kind: "struct",
    members: {
      advance: { kind: "function" },
      advance_unchecked: { kind: "function" },
      append: { kind: "function" },
      as_mut: { kind: "function" },
      capacity: { kind: "function" },
      ensure_init: { kind: "function" },
      init_mut: { kind: "function" },
      reborrow: { kind: "function" },
      set_init: { kind: "function" },
      with_unfilled_buf: { kind: "function" },
      written: { kind: "function" },
    },
  },
  BufRead: { kind: "trait", metadata: { since: "1.0.0" } },
  BufReader: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      buffer: { kind: "function", metadata: { since: "1.37.0" } },
      capacity: { kind: "function", metadata: { since: "1.46.0" } },
      get_mut: { kind: "function", metadata: { since: "1.0.0" } },
      get_ref: { kind: "function", metadata: { since: "1.0.0" } },
      into_inner: { kind: "function", metadata: { since: "1.0.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      peek: { kind: "function", metadata: { since: "unstable" } },
      seek_relative: { kind: "function", metadata: { since: "1.53.0" } },
      with_capacity: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
    },
  },
  BufWriter: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      buffer: { kind: "function", metadata: { since: "1.37.0" } },
      capacity: { kind: "function", metadata: { since: "1.46.0" } },
      get_mut: { kind: "function", metadata: { since: "1.0.0" } },
      get_ref: { kind: "function", metadata: { since: "1.0.0" } },
      into_inner: { kind: "function", metadata: { since: "1.0.0" } },
      into_parts: { kind: "function", metadata: { since: "1.56.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      with_capacity: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
    },
  },
  Bytes: { kind: "struct", metadata: { since: "1.0.0" } },
  Chain: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      get_mut: { kind: "function", metadata: { since: "1.20.0" } },
      get_ref: { kind: "function", metadata: { since: "1.20.0" } },
      into_inner: { kind: "function", metadata: { since: "1.20.0" } },
    },
  },
  const_error: { kind: "symbol", metadata: { since: "unstable" } },
  copy: { kind: "function", metadata: { since: "1.0.0" } },
  Cursor: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      get_mut: { kind: "function", metadata: { since: "1.0.0" } },
      get_ref: { kind: "function", metadata: { since: "1.0.0" } },
      into_inner: { kind: "function", metadata: { since: "1.0.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      position: { kind: "function", metadata: { since: "1.0.0" } },
      set_position: { kind: "function", metadata: { since: "1.0.0" } },
      split: { kind: "function", metadata: { since: "unstable" } },
      split_mut: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  empty: { kind: "function", metadata: { since: "1.0.0" } },
  Empty: { kind: "struct", metadata: { since: "1.0.0" } },
  Error: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      downcast: { kind: "function", metadata: { since: "1.79.0" } },
      from_raw_os_error: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      get_mut: { kind: "function", metadata: { since: "1.3.0" } },
      get_ref: { kind: "function", metadata: { since: "1.3.0" } },
      into_inner: { kind: "function", metadata: { since: "1.3.0" } },
      kind: { kind: "function", metadata: { since: "1.0.0" } },
      last_os_error: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      other: { kind: "function", associated: true, metadata: { since: "1.74.0" } },
      raw_os_error: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  ErrorKind: { kind: "enum", metadata: { since: "1.0.0" } },
  IntoInnerError: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      error: { kind: "function", metadata: { since: "1.0.0" } },
      into_error: { kind: "function", metadata: { since: "1.55.0" } },
      into_inner: { kind: "function", metadata: { since: "1.0.0" } },
      into_parts: { kind: "function", metadata: { since: "1.55.0" } },
    },
  },
  IoSlice: {
    kind: "struct", metadata: { since: "1.36.0" },
    members: {
      advance: { kind: "function", metadata: { since: "1.81.0" } },
      advance_slices: { kind: "function", associated: true, metadata: { since: "1.81.0" } },
      as_slice: { kind: "function", metadata: { since: "unstable" } },
      new: { kind: "function", associated: true, metadata: { since: "1.36.0" } },
    },
  },
  IoSliceMut: {
    kind: "struct", metadata: { since: "1.36.0" },
    members: {
      advance: { kind: "function", metadata: { since: "1.81.0" } },
      advance_slices: { kind: "function", associated: true, metadata: { since: "1.81.0" } },
      into_slice: { kind: "function", metadata: { since: "unstable" } },
      new: { kind: "function", associated: true, metadata: { since: "1.36.0" } },
    },
  },
  IsTerminal: { kind: "trait", metadata: { since: "1.70.0" } },
  Lines: { kind: "struct", metadata: { since: "1.0.0" } },
  LineWriter: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      get_mut: { kind: "function", metadata: { since: "1.0.0" } },
      get_ref: { kind: "function", metadata: { since: "1.0.0" } },
      into_inner: { kind: "function", metadata: { since: "1.0.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      with_capacity: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
    },
  },
  pipe: { kind: "function", metadata: { since: "1.87.0" } },
  PipeReader: {
    kind: "struct", metadata: { since: "1.87.0" },
    members: {
      try_clone: { kind: "function", metadata: { since: "1.87.0" } },
    },
  },
  PipeWriter: {
    kind: "struct", metadata: { since: "1.87.0" },
    members: {
      try_clone: { kind: "function", metadata: { since: "1.87.0" } },
    },
  },
  RawOsError: { kind: "type-alias", metadata: { since: "unstable" } },
  Read: { kind: "trait", metadata: { since: "1.0.0" } },
  read_to_string: { kind: "function", metadata: { since: "1.65.0" } },
  repeat: { kind: "function", metadata: { since: "1.0.0" } },
  Repeat: { kind: "struct", metadata: { since: "1.0.0" } },
  Result: { kind: "type-alias", metadata: { since: "1.0.0" } },
  Seek: { kind: "trait", metadata: { since: "1.0.0" } },
  SeekFrom: { kind: "enum", metadata: { since: "1.0.0" } },
  sink: { kind: "function", metadata: { since: "1.0.0" } },
  Sink: { kind: "struct", metadata: { since: "1.0.0" } },
  Split: { kind: "struct", metadata: { since: "1.0.0" } },
  stderr: { kind: "function", metadata: { since: "1.0.0" } },
  Stderr: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      lock: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  StderrLock: { kind: "struct", metadata: { since: "1.0.0" } },
  stdin: { kind: "function", metadata: { since: "1.0.0" } },
  Stdin: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      lines: { kind: "function", metadata: { since: "1.62.0" } },
      lock: { kind: "function", metadata: { since: "1.0.0" } },
      read_line: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  StdinLock: { kind: "struct", metadata: { since: "1.0.0" } },
  stdout: { kind: "function", metadata: { since: "1.0.0" } },
  Stdout: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      lock: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  StdoutLock: { kind: "struct", metadata: { since: "1.0.0" } },
  Take: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      get_mut: { kind: "function", metadata: { since: "1.20.0" } },
      get_ref: { kind: "function", metadata: { since: "1.20.0" } },
      into_inner: { kind: "function", metadata: { since: "1.15.0" } },
      limit: { kind: "function", metadata: { since: "1.0.0" } },
      position: { kind: "function", metadata: { since: "unstable" } },
      set_limit: { kind: "function", metadata: { since: "1.27.0" } },
    },
  },
  Write: { kind: "trait", metadata: { since: "1.0.0" } },
  WriterPanicked: {
    kind: "struct", metadata: { since: "1.56.0" },
    members: {
      into_inner: { kind: "function", metadata: { since: "1.56.0" } },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_io_prelude = {
  BufRead: { kind: "trait", metadata: { since: "1.0.0" } },
  Read: { kind: "trait", metadata: { since: "1.0.0" } },
  Seek: { kind: "trait", metadata: { since: "1.0.0" } },
  Write: { kind: "trait", metadata: { since: "1.0.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
