import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_panic = {
  abort_unwind: { kind: "function" },
  always_abort: { kind: "function", metadata: { since: "unstable" } },
  AssertUnwindSafe: { kind: "struct" },
  BacktraceStyle: { kind: "enum", metadata: { since: "unstable" } },
  catch_unwind: { kind: "function", metadata: { since: "1.9.0" } },
  get_backtrace_style: { kind: "function", metadata: { since: "unstable" } },
  Location: {
    kind: "struct",
    members: {
      caller: { kind: "function", associated: true, metadata: { since: "1.46.0" } },
      column: { kind: "function", metadata: { since: "1.25.0" } },
      file: { kind: "function", metadata: { since: "1.10.0" } },
      file_as_c_str: { kind: "function", metadata: { since: "1.92.0" } },
      line: { kind: "function", metadata: { since: "1.10.0" } },
    },
  },
  panic_any: { kind: "function", metadata: { since: "1.51.0" } },
  PanicHookInfo: {
    kind: "struct", metadata: { since: "1.81.0" },
    members: {
      can_unwind: { kind: "function", metadata: { since: "unstable" } },
      location: { kind: "function", metadata: { since: "1.10.0" } },
      payload: { kind: "function", metadata: { since: "1.10.0" } },
      payload_as_str: { kind: "function", metadata: { since: "1.91.0" } },
    },
  },
  PanicInfo: {
    kind: "type-alias", metadata: { since: "1.10.0" },
    members: {
      can_unwind: { kind: "function", metadata: { since: "unstable" } },
      location: { kind: "function", metadata: { since: "1.10.0" } },
      message: { kind: "function", metadata: { since: "1.81.0" } },
      payload: { kind: "function", metadata: { since: "1.10.0" } },
    },
  },
  PanicMessage: {
    kind: "struct", metadata: { since: "1.81.0" },
    members: {
      as_str: { kind: "function", metadata: { since: "1.81.0" } },
    },
  },
  RefUnwindSafe: { kind: "trait" },
  resume_unwind: { kind: "function", metadata: { since: "1.9.0" } },
  set_backtrace_style: { kind: "function", metadata: { since: "unstable" } },
  set_hook: { kind: "function", metadata: { since: "1.10.0" } },
  take_hook: { kind: "function", metadata: { since: "1.10.0" } },
  UnwindSafe: { kind: "trait" },
  update_hook: { kind: "function", metadata: { since: "unstable" } },
} as const satisfies Record<string, SymbolDescriptor>;
