import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_pat = {
  pattern_type: { kind: "symbol" },
  RangePattern: { kind: "trait", metadata: { since: "unstable" } },
} as const satisfies Record<string, SymbolDescriptor>;
