import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_process = {
  abort: { kind: "function", metadata: { since: "1.17.0" } },
  Child: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      id: { kind: "function", metadata: { since: "1.3.0" } },
      kill: { kind: "function", metadata: { since: "1.0.0" } },
      try_wait: { kind: "function", metadata: { since: "1.18.0" } },
      wait: { kind: "function", metadata: { since: "1.0.0" } },
      wait_with_output: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  ChildStderr: { kind: "struct", metadata: { since: "1.0.0" } },
  ChildStdin: { kind: "struct", metadata: { since: "1.0.0" } },
  ChildStdout: { kind: "struct", metadata: { since: "1.0.0" } },
  Command: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      arg: { kind: "function", metadata: { since: "1.0.0" } },
      args: { kind: "function", metadata: { since: "1.0.0" } },
      current_dir: { kind: "function", metadata: { since: "1.0.0" } },
      env: { kind: "function", metadata: { since: "1.0.0" } },
      env_clear: { kind: "function", metadata: { since: "1.0.0" } },
      env_remove: { kind: "function", metadata: { since: "1.0.0" } },
      envs: { kind: "function", metadata: { since: "1.19.0" } },
      get_args: { kind: "function", metadata: { since: "1.57.0" } },
      get_current_dir: { kind: "function", metadata: { since: "1.57.0" } },
      get_env_clear: { kind: "function", metadata: { since: "unstable" } },
      get_envs: { kind: "function", metadata: { since: "1.57.0" } },
      get_program: { kind: "function", metadata: { since: "1.57.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      output: { kind: "function", metadata: { since: "1.0.0" } },
      spawn: { kind: "function", metadata: { since: "1.0.0" } },
      status: { kind: "function", metadata: { since: "1.0.0" } },
      stderr: { kind: "function", metadata: { since: "1.0.0" } },
      stdin: { kind: "function", metadata: { since: "1.0.0" } },
      stdout: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  CommandArgs: { kind: "struct", metadata: { since: "1.57.0" } },
  CommandEnvs: { kind: "struct", metadata: { since: "1.57.0" } },
  exit: { kind: "function", metadata: { since: "1.0.0" } },
  ExitCode: {
    kind: "struct", metadata: { since: "1.61.0" },
    members: {
      exit_process: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  ExitStatus: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      code: { kind: "function", metadata: { since: "1.0.0" } },
      exit_ok: { kind: "function", metadata: { since: "unstable" } },
      success: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  ExitStatusError: {
    kind: "struct", metadata: { since: "unstable" },
    members: {
      code: { kind: "function" },
      code_nonzero: { kind: "function" },
      into_status: { kind: "function" },
    },
  },
  id: { kind: "function", metadata: { since: "1.26.0" } },
  Output: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      exit_ok: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  Stdio: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      inherit: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      makes_pipe: { kind: "function", metadata: { since: "unstable" } },
      null: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      piped: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
    },
  },
  Termination: { kind: "trait", metadata: { since: "1.61.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
