import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_profiling = {
  compiler_copy: { kind: "function", metadata: { since: "unstable" } },
  compiler_move: { kind: "function", metadata: { since: "unstable" } },
} as const satisfies Record<string, SymbolDescriptor>;
