import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_random = {
  DefaultRandomSource: { kind: "struct", metadata: { since: "unstable" } },
  Distribution: { kind: "trait", metadata: { since: "unstable" } },
  random: { kind: "function", metadata: { since: "unstable" } },
  RandomSource: { kind: "trait", metadata: { since: "unstable" } },
} as const satisfies Record<string, SymbolDescriptor>;
