import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_range = {
  Range: {
    kind: "struct",
    members: {
      contains: { kind: "function", metadata: { since: "unstable" } },
      is_empty: { kind: "function", metadata: { since: "unstable" } },
      iter: { kind: "function" },
    },
  },
  RangeFrom: {
    kind: "struct",
    members: {
      contains: { kind: "function", metadata: { since: "unstable" } },
      iter: { kind: "function" },
    },
  },
  RangeFromIter: {
    kind: "struct",
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  RangeInclusive: {
    kind: "struct",
    members: {
      contains: { kind: "function", metadata: { since: "1.95.0" } },
      is_empty: { kind: "function", metadata: { since: "1.95.0" } },
      iter: { kind: "function", metadata: { since: "1.95.0" } },
    },
  },
  RangeInclusiveIter: {
    kind: "struct", metadata: { since: "1.95.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  RangeIter: {
    kind: "struct",
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  RangeToInclusive: {
    kind: "struct",
    members: {
      contains: { kind: "function", metadata: { since: "unstable" } },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_range_legacy = {
  Range: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      contains: { kind: "function", metadata: { since: "1.35.0" } },
      is_empty: { kind: "function", metadata: { since: "1.47.0" } },
    },
  },
  RangeFrom: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      contains: { kind: "function", metadata: { since: "1.35.0" } },
    },
  },
  RangeInclusive: {
    kind: "struct", metadata: { since: "1.26.0" },
    members: {
      contains: { kind: "function", metadata: { since: "1.35.0" } },
      end: { kind: "function", metadata: { since: "1.27.0" } },
      into_inner: { kind: "function", metadata: { since: "1.27.0" } },
      is_empty: { kind: "function", metadata: { since: "1.47.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.27.0" } },
      start: { kind: "function", metadata: { since: "1.27.0" } },
    },
  },
  RangeToInclusive: {
    kind: "struct", metadata: { since: "1.26.0" },
    members: {
      contains: { kind: "function", metadata: { since: "1.35.0" } },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;
