import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_str = {
  Bytes: { kind: "struct", metadata: { since: "1.0.0" } },
  BytesIsNotEmpty: { kind: "struct" },
  CharEscapeDebugContinue: { kind: "struct" },
  CharEscapeDefault: { kind: "struct" },
  CharEscapeUnicode: { kind: "struct" },
  CharIndices: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      as_str: { kind: "function", metadata: { since: "1.4.0" } },
      offset: { kind: "function", metadata: { since: "1.82.0" } },
    },
  },
  Chars: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      as_str: { kind: "function", metadata: { since: "1.4.0" } },
    },
  },
  EncodeUtf16: { kind: "struct", metadata: { since: "1.8.0" } },
  EscapeDebug: { kind: "struct", metadata: { since: "1.34.0" } },
  EscapeDefault: { kind: "struct", metadata: { since: "1.34.0" } },
  EscapeUnicode: { kind: "struct", metadata: { since: "1.34.0" } },
  from_boxed_utf8_unchecked: { kind: "function", metadata: { since: "1.20.0" } },
  from_raw_parts: { kind: "function", metadata: { since: "unstable" } },
  from_raw_parts_mut: { kind: "function", metadata: { since: "unstable" } },
  from_utf8: { kind: "function", metadata: { since: "1.0.0" } },
  from_utf8_mut: { kind: "function", metadata: { since: "1.20.0" } },
  from_utf8_unchecked: { kind: "function", metadata: { since: "1.0.0" } },
  from_utf8_unchecked_mut: { kind: "function", metadata: { since: "1.20.0" } },
  FromStr: { kind: "trait", metadata: { since: "1.0.0" } },
  IsAsciiWhitespace: { kind: "struct" },
  IsNotEmpty: { kind: "struct" },
  IsWhitespace: { kind: "struct" },
  Lines: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  LinesAny: { kind: "struct", metadata: { since: "1.0.0" } },
  LinesMap: { kind: "struct" },
  Matches: { kind: "struct", metadata: { since: "1.2.0" } },
  MatchIndices: { kind: "struct", metadata: { since: "1.5.0" } },
  next_code_point: { kind: "function", metadata: { since: "unstable" } },
  ParseBoolError: { kind: "struct", metadata: { since: "1.0.0" } },
  RMatches: { kind: "struct", metadata: { since: "1.2.0" } },
  RMatchIndices: { kind: "struct", metadata: { since: "1.5.0" } },
  RSplit: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  RSplitN: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  RSplitTerminator: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  Split: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  SplitAsciiWhitespace: {
    kind: "struct", metadata: { since: "1.34.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  SplitInclusive: {
    kind: "struct", metadata: { since: "1.51.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  SplitN: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  SplitTerminator: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  SplitWhitespace: {
    kind: "struct", metadata: { since: "1.1.0" },
    members: {
      remainder: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  UnsafeBytesToStr: { kind: "struct" },
  utf8_char_width: { kind: "function", metadata: { since: "unstable" } },
  Utf8Chunk: {
    kind: "struct", metadata: { since: "1.79.0" },
    members: {
      invalid: { kind: "function", metadata: { since: "1.79.0" } },
      valid: { kind: "function", metadata: { since: "1.79.0" } },
    },
  },
  Utf8Chunks: { kind: "struct", metadata: { since: "1.79.0" } },
  Utf8Error: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      error_len: { kind: "function", metadata: { since: "1.20.0" } },
      valid_up_to: { kind: "function", metadata: { since: "1.5.0" } },
    },
  },
} as const satisfies Record<string, SymbolDescriptor>;

export const mod_str_pattern = {
  CharArrayRefSearcher: { kind: "struct" },
  CharArraySearcher: { kind: "struct" },
  CharPredicateSearcher: { kind: "struct" },
  CharSearcher: { kind: "struct" },
  CharSliceSearcher: { kind: "struct" },
  DoubleEndedSearcher: { kind: "trait" },
  EmptyNeedle: { kind: "struct" },
  MultiCharEqPattern: { kind: "struct" },
  MultiCharEqSearcher: { kind: "struct" },
  Pattern: { kind: "trait" },
  ReverseSearcher: { kind: "trait" },
  Searcher: { kind: "trait" },
  SearchStep: { kind: "enum" },
  StrSearcher: { kind: "struct" },
  StrSearcherImpl: { kind: "enum" },
  TwoWaySearcher: { kind: "struct" },
  Utf8Pattern: { kind: "enum" },
} as const satisfies Record<string, SymbolDescriptor>;
