import type { SymbolDescriptor } from "../../create-crate.js";

// Generated by scripts/generate-crate-descriptor.ts
// Source: rustdoc JSON format version 57

export const mod_thread = {
  AccessError: { kind: "struct", metadata: { since: "1.26.0" } },
  add_spawn_hook: { kind: "function", metadata: { since: "unstable" } },
  available_parallelism: { kind: "function", metadata: { since: "1.59.0" } },
  Builder: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      name: { kind: "function", metadata: { since: "1.0.0" } },
      new: { kind: "function", associated: true, metadata: { since: "1.0.0" } },
      no_hooks: { kind: "function", metadata: { since: "unstable" } },
      spawn: { kind: "function", metadata: { since: "1.0.0" } },
      spawn_scoped: { kind: "function", metadata: { since: "1.63.0" } },
      spawn_unchecked: { kind: "function", metadata: { since: "1.82.0" } },
      stack_size: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  current: { kind: "function", metadata: { since: "1.0.0" } },
  current_id: { kind: "function", metadata: { since: "unstable" } },
  JoinHandle: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      is_finished: { kind: "function", metadata: { since: "1.61.0" } },
      join: { kind: "function", metadata: { since: "1.0.0" } },
      thread: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  LocalKey: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      get: { kind: "function", metadata: { since: "1.73.0" } },
      replace: { kind: "function", metadata: { since: "1.73.0" } },
      set: { kind: "function", metadata: { since: "1.73.0" } },
      take: { kind: "function", metadata: { since: "1.73.0" } },
      try_with: { kind: "function", metadata: { since: "1.26.0" } },
      update: { kind: "function", metadata: { since: "unstable" } },
      with: { kind: "function", metadata: { since: "1.0.0" } },
      with_borrow: { kind: "function", metadata: { since: "1.73.0" } },
      with_borrow_mut: { kind: "function", metadata: { since: "1.73.0" } },
    },
  },
  panicking: { kind: "function", metadata: { since: "1.0.0" } },
  park: { kind: "function", metadata: { since: "1.0.0" } },
  park_timeout: { kind: "function", metadata: { since: "1.4.0" } },
  park_timeout_ms: { kind: "function", metadata: { since: "1.0.0" } },
  Result: { kind: "type-alias", metadata: { since: "1.0.0" } },
  scope: { kind: "function", metadata: { since: "1.63.0" } },
  Scope: {
    kind: "struct", metadata: { since: "1.63.0" },
    members: {
      spawn: { kind: "function", metadata: { since: "1.63.0" } },
    },
  },
  ScopedJoinHandle: {
    kind: "struct", metadata: { since: "1.63.0" },
    members: {
      is_finished: { kind: "function", metadata: { since: "1.63.0" } },
      join: { kind: "function", metadata: { since: "1.63.0" } },
      thread: { kind: "function", metadata: { since: "1.63.0" } },
    },
  },
  sleep: { kind: "function", metadata: { since: "1.4.0" } },
  sleep_ms: { kind: "function", metadata: { since: "1.0.0" } },
  sleep_until: { kind: "function", metadata: { since: "unstable" } },
  spawn: { kind: "function", metadata: { since: "1.0.0" } },
  Thread: {
    kind: "struct", metadata: { since: "1.0.0" },
    members: {
      from_raw: { kind: "function", associated: true, metadata: { since: "unstable" } },
      id: { kind: "function", metadata: { since: "1.19.0" } },
      into_raw: { kind: "function", metadata: { since: "unstable" } },
      name: { kind: "function", metadata: { since: "1.0.0" } },
      unpark: { kind: "function", metadata: { since: "1.0.0" } },
    },
  },
  ThreadId: {
    kind: "struct", metadata: { since: "1.19.0" },
    members: {
      as_u64: { kind: "function", metadata: { since: "unstable" } },
    },
  },
  yield_now: { kind: "function", metadata: { since: "1.0.0" } },
} as const satisfies Record<string, SymbolDescriptor>;
