import { stc } from "@alloy-js/core";
import * as base from "../index.js";

export const ArrayExpression = stc(base.ArrayExpression);
export const BarrelFile = stc(base.BarrelFile);
export const Block = stc(base.Block);
export const Declaration = stc(base.Declaration);
export const EnumDeclaration = stc(base.EnumDeclaration);
export const EnumMember = stc(base.EnumMember);
export const ExportStatement = stc(base.ExportStatement);
export const FunctionDeclaration = stc(base.FunctionDeclaration);
export const ImportStatement = stc(base.ImportStatement);
export const ImportStatements = stc(base.ImportStatements);
export const InterfaceDeclaration = stc(base.InterfaceDeclaration);
export const InterfaceExpression = stc(base.InterfaceExpression);
export const InterfaceMember = stc(base.InterfaceMember);
export const Name = stc(base.Name);
export const ObjectExpression = stc(base.ObjectExpression);
export const ObjectProperty = stc(base.ObjectProperty);
export const PackageDirectory = stc(base.PackageDirectory);
export const PackageJsonFile = stc(base.PackageJsonFile);
export const Reference = stc(base.Reference);
export const SourceFile = stc(base.SourceFile);
export const TSConfigJson = stc(base.TSConfigJson);
export const TypeDeclaration = stc(base.TypeDeclaration);
export const ValueExpression = stc(base.ValueExpression);
export const VarDeclaration = stc(base.VarDeclaration);
