name: Pull Request Checks (Pinterest)
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Generate docs
        working-directory: ./packages/docs
        run: pnpm run generate-docs

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: pnpm install
        name: Install dependencies

      - run: pnpm run format:check
        name: Check formatting

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - run: pnpm install
        name: Install dependencies

      - run: pnpm run lint
        name: Lint
